//! No-toolchain integration checks for snapshot store ownership parsing.

#[cfg(test)]
mod tests {
    use std::fs;

    use libruskel::{Result, SnapshotMode, SnapshotStore};

    const MARKER: &str = "# @generated by `ruskel-snapshot`; do not edit.\nformat = 1\ntoolchain = \"nightly-2099-01-01\"\ntarget = \"fixture-target\"\ndefault_features = true\nall_features = false\nfeatures = []\n";

    #[test]
    fn stored_profile_does_not_require_an_installed_toolchain() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        fs::create_dir(&output)?;
        fs::write(output.join(".ruskel-snapshot.toml"), MARKER)?;

        let store = SnapshotStore::open(&output, SnapshotMode::Check)?;
        let profile = store.profile().expect("stored profile");
        assert_eq!(profile.toolchain(), "nightly-2099-01-01");
        assert_eq!(profile.target(), "fixture-target");
        Ok(())
    }

    #[test]
    fn unsupported_marker_is_rejected_without_mutation() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        fs::create_dir(&output)?;
        let unsupported = MARKER.replace("format = 1", "format = 9");
        fs::write(output.join(".ruskel-snapshot.toml"), &unsupported)?;

        assert!(SnapshotStore::open(&output, SnapshotMode::Check).is_err());
        assert_eq!(
            fs::read_to_string(output.join(".ruskel-snapshot.toml"))?,
            unsupported
        );
        Ok(())
    }
}
