//! Crate cards and the workspace catalogue index.

use cargo::core::dependency::DepKind;

use super::{
    GENERATED_SOURCE_HEADER,
    discovery::{DiscoveredPackage, Discovery, WorkspaceDependency, WorkspaceDependent},
    model::{ApiSnapshot, SnapshotFeatures},
};

/// Exact ownership warning at the start of the generated index.
pub const GENERATED_INDEX_HEADER: &str = "<!-- @generated by `ruskel-snapshot`; do not edit. -->";

/// Build the complete prefix passed to the Rust snapshot renderer.
pub fn crate_card(package: &DiscoveredPackage, unnameable: &[String]) -> String {
    let mut card = String::from(GENERATED_SOURCE_HEADER.trim_end());
    card.push_str("\n//\n");
    for (key, value) in card_fields(package, unnameable) {
        card.push_str(&format!("// {key}: {value}\n"));
    }
    card.push('\n');
    card
}

/// Render one index for the same ordered crates as the capture.
pub fn workspace_index(discovery: &Discovery, snapshot: &ApiSnapshot) -> String {
    let mut output = format!(
        "{GENERATED_INDEX_HEADER}\n\n# API catalogue\n\nCapture features: {}. Each crate follows its workspace dependencies. Dependents outside\nthis workspace are not listed.\n",
        feature_policy(snapshot.profile().features()),
    );
    for captured in snapshot.crates() {
        let package = discovery
            .packages
            .iter()
            .find(|package| package.package_name == captured.package())
            .expect("captured package has discovery metadata");
        output.push_str(&format!("\n## {}\n\n", captured.package()));
        if !captured.summary().is_empty() {
            output.push_str(captured.summary());
            output.push_str("\n\n");
        }
        for (key, value) in card_fields(package, captured.unnameable()) {
            if key != "Package" {
                output.push_str(&format!("- {key}: {value}\n"));
            }
        }
        output.push_str(&format!("- Items: {}\n", captured.items()));
        let mut exposes = captured.exposes().to_vec();
        exposes.sort();
        exposes.dedup();
        output.push_str(&format!("- Exposes: {}\n", list_or_none(exposes)));
    }
    if !discovery.binary_packages.is_empty() {
        output.push_str("\n## Binary-only packages\n");
        for package in &discovery.binary_packages {
            output.push_str(&format!(
                "\n- {}: workspace dependencies: {}\n",
                package.name,
                dependency_list(&package.workspace_dependencies),
            ));
        }
    }
    output
}

/// Collect ordered crate facts shared by the card and workspace index.
fn card_fields(package: &DiscoveredPackage, unnameable: &[String]) -> Vec<(&'static str, String)> {
    let mut fields = vec![("Package", package.package_name.clone())];
    if package.crate_name != package.package_name.replace('-', "_") {
        fields.push(("Crate", package.crate_name.clone()));
    }
    fields.push(("Publish", package.publish.clone()));
    if !package.features.is_empty() {
        fields.push((
            "Declared features",
            list_or_none(package.features.iter().map(String::as_str)),
        ));
    }
    if !package.binaries.is_empty() {
        fields.push((
            "Binaries",
            list_or_none(package.binaries.iter().map(String::as_str)),
        ));
    }
    fields.push((
        "Workspace dependencies",
        dependency_list(&package.workspace_dependencies),
    ));
    fields.push((
        "Workspace dependents",
        dependent_list(&package.workspace_dependents),
    ));
    if !unnameable.is_empty() {
        let mut names = unnameable.to_vec();
        names.sort();
        names.dedup();
        fields.push(("Unnameable", list_or_none(names)));
    }
    fields
}

/// Format direct workspace dependencies and optional edges.
fn dependency_list(dependencies: &[WorkspaceDependency]) -> String {
    list_or_none(dependencies.iter().map(|dependency| {
        if dependency.optional {
            format!("{} (optional)", dependency.package)
        } else {
            dependency.package.clone()
        }
    }))
}

/// Format workspace callers and their dependency kinds.
fn dependent_list(dependents: &[WorkspaceDependent]) -> String {
    list_or_none(dependents.iter().map(|dependent| match dependent.kind {
        DepKind::Normal => dependent.package.clone(),
        DepKind::Development => format!("{} (dev)", dependent.package),
        DepKind::Build => format!("{} (build)", dependent.package),
    }))
}

/// Join an ordered list or state that it has no entries.
fn list_or_none<I, S>(values: I) -> String
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let values = values
        .into_iter()
        .map(|value| value.as_ref().to_string())
        .collect::<Vec<_>>();
    if values.is_empty() {
        "none".to_string()
    } else {
        values.join(", ")
    }
}

/// Describe the Cargo feature policy of one capture.
fn feature_policy(features: &SnapshotFeatures) -> String {
    if features.all_features() {
        "all".to_string()
    } else {
        let mut parts = Vec::new();
        if features.default_features() {
            parts.push("default".to_string());
        }
        parts.extend(features.features().iter().cloned());
        list_or_none(parts)
    }
}

#[cfg(test)]
mod tests {
    use std::{
        collections::{BTreeMap, BTreeSet},
        path::PathBuf,
    };

    use super::*;
    use crate::snapshot::{CrateSnapshot, SnapshotProfile};

    #[test]
    fn card_and_index_keep_dependency_facts_in_one_order() {
        let package = DiscoveredPackage {
            manifest_path: PathBuf::from("/app/Cargo.toml"),
            package_name: "app".into(),
            crate_name: "app_library".into(),
            filename: "app.rs".into(),
            features: BTreeSet::from(["serde".into()]),
            publish: "no".into(),
            binaries: vec!["app-cli".into()],
            workspace_dependencies: vec![WorkspaceDependency {
                package: "core".into(),
                optional: true,
            }],
            workspace_dependents: vec![WorkspaceDependent {
                package: "tool".into(),
                kind: DepKind::Build,
            }],
            dependency_aliases: BTreeMap::new(),
        };
        let unnameable = vec!["crate::private::Hidden".into()];
        let card = crate_card(&package, &unnameable);
        assert!(card.starts_with("// @generated by `ruskel-snapshot`; do not edit.\n//\n"));
        assert!(card.contains("// Crate: app_library\n"));
        assert!(card.contains("// Workspace dependencies: core (optional)\n"));
        assert!(card.contains("// Workspace dependents: tool (build)\n"));
        assert!(card.contains("// Unnameable: crate::private::Hidden\n"));

        let snapshot = ApiSnapshot {
            profile: SnapshotProfile::fixture(),
            crates: vec![CrateSnapshot {
                package: "app".into(),
                crate_name: "app_library".into(),
                filename: "app.rs".into(),
                contents: card,
                summary: "Application API.".into(),
                items: 7,
                exposes: vec!["egui".into()],
                unnameable,
            }],
            skipped_packages: vec!["bin-only".into()],
            index: String::new(),
        };
        let discovery = Discovery {
            packages: vec![package],
            skipped_packages: vec!["bin-only".into()],
            binary_packages: vec![super::super::discovery::BinaryPackage {
                name: "bin-only".into(),
                workspace_dependencies: vec![WorkspaceDependency {
                    package: "app".into(),
                    optional: false,
                }],
            }],
        };
        let index = workspace_index(&discovery, &snapshot);
        assert!(index.starts_with(
            "<!-- @generated by `ruskel-snapshot`; do not edit. -->\n\n# API catalogue\n"
        ));
        assert!(index.contains("Capture features: default."));
        assert!(index.contains("Application API.\n\n- Crate: app_library"));
        assert!(index.contains("- Items: 7\n- Exposes: egui\n"));
        assert!(index.contains("- bin-only: workspace dependencies: app\n"));
    }
}
