//! Format 1 ownership manifest parsing and serialization.

use std::{collections::BTreeSet, path::Path, str};

use serde::Deserialize;

use crate::{
    error::{Result, RuskelError},
    snapshot::{CrateSnapshot, SnapshotFeatures, SnapshotProfile},
};

/// Reserved ownership marker filename.
pub(super) const MARKER_FILENAME: &str = ".ruskel-snapshot.toml";
/// Exact first line that claims generated-tree ownership.
const GENERATED_LINE: &str = "# @generated by `ruskel-snapshot`; do not edit.";

/// Validated in-memory format 1 marker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct Manifest {
    /// Stored capture profile.
    pub(super) profile: SnapshotProfile,
    /// Canonically ordered crate identities.
    pub(super) crates: Vec<ManifestCrate>,
}

/// One validated managed crate identity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct ManifestCrate {
    /// Cargo package name.
    pub(super) package: String,
    /// Rust library target name.
    pub(super) crate_name: String,
    /// Owned relative file path.
    pub(super) file: String,
}

/// Untrusted deserialized marker fields.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawManifest {
    /// Declared storage format.
    format: u32,
    /// Stored portable toolchain.
    toolchain: String,
    /// Stored compilation target.
    target: String,
    /// Stored default-feature selection.
    default_features: bool,
    /// Stored all-feature selection.
    all_features: bool,
    /// Stored sorted feature selectors.
    features: Vec<String>,
    /// Stored crate identities.
    #[serde(default)]
    crates: Vec<RawCrate>,
}

/// One untrusted deserialized crate identity.
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct RawCrate {
    /// Cargo package name.
    package: String,
    /// Rust library target name.
    #[serde(rename = "crate")]
    crate_name: String,
    /// Claimed managed file path.
    file: String,
}

impl Manifest {
    /// Build the marker for one complete in-memory capture.
    pub(super) fn from_snapshot(profile: &SnapshotProfile, crates: &[CrateSnapshot]) -> Self {
        Self {
            profile: profile.clone(),
            crates: crates
                .iter()
                .map(|entry| ManifestCrate {
                    package: entry.package().to_string(),
                    crate_name: entry.crate_name().to_string(),
                    file: entry.filename().to_string(),
                })
                .collect(),
        }
    }

    /// Parse and validate untrusted marker bytes.
    pub(super) fn parse(bytes: &[u8], path: &Path) -> Result<Self> {
        let text = str::from_utf8(bytes)
            .map_err(|error| store_error(path, format!("marker is not UTF-8: {error}")))?;
        if text.lines().next() != Some(GENERATED_LINE) {
            return Err(store_error(
                path,
                "marker does not have the generated ownership line",
            ));
        }
        let raw: RawManifest = toml::from_str(text)
            .map_err(|error| store_error(path, format!("invalid marker: {error}")))?;
        let features =
            SnapshotFeatures::new(raw.default_features, raw.all_features, raw.features.clone())
                .map_err(|error| store_error(path, error.to_string()))?;
        if features.features() != raw.features {
            return Err(store_error(
                path,
                "marker features are not sorted and unique",
            ));
        }
        let profile = SnapshotProfile::from_marker(raw.format, raw.toolchain, raw.target, features)
            .map_err(|error| store_error(path, error.to_string()))?;

        let mut files = BTreeSet::new();
        let mut folded = BTreeSet::new();
        let mut crates = Vec::with_capacity(raw.crates.len());
        let mut previous = None;
        for entry in raw.crates {
            validate_identity(&entry, path)?;
            if !files.insert(entry.file.clone()) || !folded.insert(entry.file.to_lowercase()) {
                return Err(store_error(
                    path,
                    format!("duplicate managed file '{}'", entry.file),
                ));
            }
            let key = (
                entry.package.clone(),
                entry.crate_name.clone(),
                entry.file.clone(),
            );
            if previous.as_ref().is_some_and(|previous| previous >= &key) {
                return Err(store_error(
                    path,
                    "crate entries are not in canonical order",
                ));
            }
            previous = Some(key);
            crates.push(ManifestCrate {
                package: entry.package,
                crate_name: entry.crate_name,
                file: entry.file,
            });
        }
        Ok(Self { profile, crates })
    }

    /// Serialize the exact canonical format 1 marker.
    pub(super) fn serialize(&self) -> Vec<u8> {
        let features = self
            .profile
            .features()
            .features()
            .iter()
            .map(|feature| toml_string(feature))
            .collect::<Vec<_>>()
            .join(", ");
        let mut text = format!(
            "{GENERATED_LINE}\nformat = {}\ntoolchain = {}\ntarget = {}\ndefault_features = {}\nall_features = {}\nfeatures = [{features}]\n",
            self.profile.format(),
            toml_string(self.profile.toolchain()),
            toml_string(self.profile.target()),
            self.profile.features().default_features(),
            self.profile.features().all_features(),
        );
        for entry in &self.crates {
            text.push_str(&format!(
                "\n[[crates]]\npackage = {}\ncrate = {}\nfile = {}\n",
                toml_string(&entry.package),
                toml_string(&entry.crate_name),
                toml_string(&entry.file),
            ));
        }
        text.into_bytes()
    }
}

/// Validate one marker-to-file identity mapping.
fn validate_identity(entry: &RawCrate, marker: &Path) -> Result<()> {
    if entry.package.is_empty() || entry.crate_name.is_empty() {
        return Err(store_error(marker, "crate identity cannot be empty"));
    }
    let file = Path::new(&entry.file);
    if entry.file == MARKER_FILENAME
        || file.is_absolute()
        || file.components().count() != 1
        || entry.file == "."
        || entry.file == ".."
    {
        return Err(store_error(
            marker,
            format!("invalid managed path '{}'", entry.file),
        ));
    }
    let expected = format!("{}.rs", entry.package);
    if entry.file != expected {
        return Err(store_error(
            marker,
            format!(
                "managed file '{}' does not match package '{}'",
                entry.file, entry.package
            ),
        ));
    }
    Ok(())
}

/// Quote one marker value as a TOML basic string.
fn toml_string(value: &str) -> String {
    format!("{value:?}")
}

/// Build the exact crate source header for one marker identity.
pub(super) fn expected_header(entry: &ManifestCrate) -> String {
    format!(
        "// @generated by `ruskel-snapshot`; do not edit.\n// snapshot-format: 1\n// package: {}\n// crate: {}\n\n",
        entry.package, entry.crate_name
    )
}

/// Build a path-specific snapshot store error.
fn store_error(path: &Path, message: impl Into<String>) -> RuskelError {
    RuskelError::SnapshotStore {
        path: path.to_path_buf(),
        message: message.into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parser_does_not_inspect_local_toolchains() -> Result<()> {
        let bytes = b"# @generated by `ruskel-snapshot`; do not edit.\nformat = 1\ntoolchain = \"nightly-2099-01-01\"\ntarget = \"invented-target\"\ndefault_features = true\nall_features = false\nfeatures = []\n";
        let manifest = Manifest::parse(bytes, Path::new("marker"))?;
        assert_eq!(manifest.profile.toolchain(), "nightly-2099-01-01");
        assert_eq!(manifest.serialize(), bytes);
        Ok(())
    }

    #[test]
    fn parser_rejects_noncanonical_owned_paths() {
        let base = "# @generated by `ruskel-snapshot`; do not edit.\nformat = 1\ntoolchain = \"nightly-2099-01-01\"\ntarget = \"fixture\"\ndefault_features = true\nall_features = false\nfeatures = []\n\n[[crates]]\npackage = \"alpha\"\ncrate = \"alpha\"\nfile = ";
        for file in ["\"../alpha.rs\"\n", "\"/alpha.rs\"\n", "\"other.rs\"\n"] {
            assert!(
                Manifest::parse(format!("{base}{file}").as_bytes(), Path::new("marker")).is_err()
            );
        }
    }
}
