//! Canonical workspace API snapshot capture.

/// Exact ownership warning at the start of each generated Rust file.
const GENERATED_SOURCE_HEADER: &str = "// @generated by `ruskel-snapshot`; do not edit.\n\n";

/// Serial in-memory capture orchestration.
pub mod capture;
/// Cargo workspace discovery and feature routing.
mod discovery;
/// Public snapshot value types and profile resolution.
mod model;
/// Safe snapshot tree comparison and persistence.
mod store;

pub use capture::capture;
pub use model::{
    ApiSnapshot, CrateSnapshot, SnapshotFeatures, SnapshotProfile, SnapshotProfileOptions,
    SnapshotRequest,
};
pub use store::{SnapshotChange, SnapshotChangeKind, SnapshotMode, SnapshotReport, SnapshotStore};
