//! Safe snapshot tree comparison and persistence.

use std::{
    collections::BTreeMap,
    fs::{self, File},
    io::{ErrorKind, Result as IoResult, Write},
    path::{Path, PathBuf},
};

use tempfile::{Builder, TempDir};

use crate::{
    error::{Result, RuskelError},
    snapshot::ApiSnapshot,
};

/// Marker emitted by older versions and removed during the next update.
const LEGACY_MARKER_FILENAME: &str = ".ruskel-snapshot.toml";
/// Exact first line that identifies an old generated marker.
const LEGACY_MARKER_HEADER: &str = "# @generated by `ruskel-snapshot`; do not edit.";
/// Exact first line that identifies an owned generated Rust file.
const GENERATED_SOURCE_LINE: &str = "// @generated by `ruskel-snapshot`; do not edit.";

/// Persistence behavior for one snapshot destination.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SnapshotMode {
    /// Replace the generated tree when captured bytes differ.
    Update,
    /// Compare captured bytes without changing the generated tree.
    Check,
}

/// One typed snapshot comparison result.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SnapshotChangeKind {
    /// The captured entry does not exist in the stored tree.
    Added,
    /// The captured and stored entry bytes differ.
    Changed,
    /// A previously managed entry is no longer captured.
    Removed,
    /// The captured and stored entry bytes are identical.
    Unchanged,
    /// The destination contains an entry that Ruskel does not own.
    Unexpected,
    /// A bounded backup shows an interrupted directory swap.
    Interrupted,
}

/// One path and its typed comparison result.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SnapshotChange {
    /// Path relative to the snapshot parent.
    path: PathBuf,
    /// Typed comparison result.
    kind: SnapshotChangeKind,
}

impl SnapshotChange {
    /// Return the path relative to the snapshot parent.
    pub fn path(&self) -> &Path {
        &self.path
    }

    /// Return the comparison result.
    pub fn kind(&self) -> SnapshotChangeKind {
        self.kind
    }
}

/// Complete ordered result from one snapshot synchronization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SnapshotReport {
    /// Ordered file, drift, and interruption results.
    changes: Vec<SnapshotChange>,
    /// Ordered binary-only package names.
    skipped_packages: Vec<String>,
}

impl SnapshotReport {
    /// Return file results in display order.
    pub fn changes(&self) -> &[SnapshotChange] {
        &self.changes
    }

    /// Return skipped binary-only packages in package order.
    pub fn skipped_packages(&self) -> &[String] {
        &self.skipped_packages
    }

    /// Return whether the destination matches the captured snapshot.
    pub fn is_current(&self) -> bool {
        self.changes
            .iter()
            .all(|change| change.kind == SnapshotChangeKind::Unchanged)
    }
}

/// One physically resolved snapshot destination.
#[derive(Debug)]
pub struct SnapshotStore {
    /// Physical output path.
    path: PathBuf,
    /// Exact bounded sibling backup prefix.
    backup_prefix: String,
    /// Selected persistence mode.
    mode: SnapshotMode,
    /// Output or interrupted backup used for comparisons.
    logical_path: PathBuf,
    /// Ordered interrupted backup report paths.
    interrupted: Vec<PathBuf>,
}

/// Validated filesystem state for one generated tree.
#[derive(Debug)]
struct TreeState {
    /// Generated Rust files keyed by relative path.
    generated: BTreeMap<String, Vec<u8>>,
    /// Whether the tree contains the generated legacy marker.
    legacy_marker: bool,
    /// Sorted entries that Ruskel does not own.
    unexpected: Vec<PathBuf>,
}

impl SnapshotStore {
    /// Open and validate one generated destination.
    pub fn open(path: impl AsRef<Path>, mode: SnapshotMode) -> Result<Self> {
        let (path, backup_prefix) = physical_identity(path.as_ref())?;
        let backups = find_backups(&path, &backup_prefix)?;
        if backups.len() > 1 {
            return Err(store_error(
                &path,
                format!("multiple interrupted backups use prefix '{backup_prefix}'"),
            ));
        }

        let mut interrupted = Vec::new();
        let backup_state = backups
            .first()
            .map(|backup| validate_tree(backup, false).map(|state| (backup, state)))
            .transpose()?;

        if mode == SnapshotMode::Update {
            if let Some((backup, _)) = backup_state {
                if path.exists() {
                    validate_tree(&path, false)?;
                    remove_validated_tree(backup, &path)?;
                } else {
                    fs::rename(backup, &path).map_err(|error| {
                        store_error(
                            &path,
                            format!("failed to restore interrupted backup: {error}"),
                        )
                    })?;
                }
            }
        } else if let Some((backup, _)) = &backup_state {
            interrupted.push(
                backup
                    .file_name()
                    .map(PathBuf::from)
                    .unwrap_or_else(|| backup.to_path_buf()),
            );
        }

        validate_tree(&path, mode == SnapshotMode::Check)?;
        let logical_path = if mode == SnapshotMode::Check && !path.exists() {
            backup_state
                .map(|(backup, _)| backup.to_path_buf())
                .unwrap_or_else(|| path.clone())
        } else {
            path.clone()
        };
        Ok(Self {
            path,
            backup_prefix,
            mode,
            logical_path,
            interrupted,
        })
    }

    /// Compare or atomically update the destination with one captured snapshot.
    pub fn sync(&self, snapshot: &ApiSnapshot) -> Result<SnapshotReport> {
        let desired = desired_files(snapshot);
        let actual = validate_tree(&self.path, self.mode == SnapshotMode::Check)?;

        let current = if self.logical_path == self.path {
            actual
        } else {
            validate_tree(&self.logical_path, true)?
        };

        let report = report(
            &current,
            &desired,
            snapshot.skipped_packages(),
            &self.interrupted,
        );
        if self.mode == SnapshotMode::Check || report.is_current() {
            return Ok(report);
        }
        let temporary = write_complete_tree(&self.path, &desired)?;
        let check = validate_tree(temporary.path(), false)?;
        if !tree_is_identical(&check, &desired) {
            return Err(store_error(
                &self.path,
                "temporary snapshot tree failed validation",
            ));
        }
        commit_tree(&self.path, &self.backup_prefix, temporary)?;
        Ok(report)
    }
}

/// Resolve a caller spelling to one physical output and backup identity.
fn physical_identity(input: &Path) -> Result<(PathBuf, String)> {
    if input.file_name().is_none() {
        return Err(store_error(
            input,
            "destination must have a final path component",
        ));
    }
    if let Ok(metadata) = fs::symlink_metadata(input)
        && metadata.file_type().is_symlink()
    {
        return Err(store_error(input, "destination cannot be a symlink"));
    }
    let path = if input.exists() {
        input.canonicalize().map_err(|error| {
            store_error(
                input,
                format!("failed to canonicalize destination: {error}"),
            )
        })?
    } else {
        let parent = input.parent().unwrap_or_else(|| Path::new("."));
        let parent = parent.canonicalize().map_err(|error| {
            store_error(
                input,
                format!("failed to canonicalize destination parent: {error}"),
            )
        })?;
        parent.join(input.file_name().expect("checked final component"))
    };
    let name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| store_error(&path, "destination name must be UTF-8"))?;
    let backup_prefix = format!(".{name}.ruskel-snapshot-backup-");
    Ok((path, backup_prefix))
}

/// Find bounded sibling backup candidates in lexical order.
fn find_backups(path: &Path, prefix: &str) -> Result<Vec<PathBuf>> {
    let parent = path.parent().expect("destination has parent");
    let mut backups = fs::read_dir(parent)
        .map_err(|error| store_error(path, format!("failed to inspect snapshot parent: {error}")))?
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| {
            entry
                .file_name()
                .to_str()
                .filter(|name| name.starts_with(prefix))
                .map(|_| entry.path())
        })
        .collect::<Vec<_>>();
    backups.sort();
    Ok(backups)
}

/// Classify immediate files by their generated ownership header.
fn validate_tree(path: &Path, allow_unexpected: bool) -> Result<TreeState> {
    let metadata = match fs::symlink_metadata(path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == ErrorKind::NotFound => {
            return Ok(TreeState {
                generated: BTreeMap::new(),
                legacy_marker: false,
                unexpected: Vec::new(),
            });
        }
        Err(error) => {
            return Err(store_error(
                path,
                format!("failed to inspect destination: {error}"),
            ));
        }
    };
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(store_error(
            path,
            "destination must be a directory and not a symlink",
        ));
    }
    let mut generated = BTreeMap::new();
    let mut legacy_marker = false;
    let mut unexpected = Vec::new();
    for entry in directory_entries(path)? {
        let file = path.join(&entry);
        let metadata = fs::symlink_metadata(&file).map_err(|error| {
            store_error(
                &file,
                format!("failed to inspect destination entry: {error}"),
            )
        })?;
        if metadata.file_type().is_symlink() || !metadata.is_file() {
            unexpected.push(entry);
            continue;
        }
        let bytes = fs::read(&file)
            .map_err(|error| store_error(&file, format!("failed to read file: {error}")))?;
        let Some(name) = entry.to_str() else {
            unexpected.push(entry);
            continue;
        };
        if name == LEGACY_MARKER_FILENAME && has_header(&bytes, LEGACY_MARKER_HEADER) {
            legacy_marker = true;
        } else if file.extension().and_then(|extension| extension.to_str()) == Some("rs")
            && has_header(&bytes, GENERATED_SOURCE_LINE)
        {
            generated.insert(name.to_string(), bytes);
        } else {
            unexpected.push(entry);
        }
    }
    unexpected.sort();
    if !allow_unexpected && let Some(entry) = unexpected.first() {
        return Err(store_error(
            path,
            format!("destination contains unowned entry '{}'", entry.display()),
        ));
    }
    Ok(TreeState {
        generated,
        legacy_marker,
        unexpected,
    })
}

/// Return whether bytes begin with one exact generated ownership line.
fn has_header(bytes: &[u8], header: &str) -> bool {
    bytes
        .strip_prefix(header.as_bytes())
        .is_some_and(|rest| rest.starts_with(b"\n") || rest.starts_with(b"\r\n"))
}

/// Return each immediate destination entry as a relative path.
fn directory_entries(path: &Path) -> Result<Vec<PathBuf>> {
    fs::read_dir(path)
        .map_err(|error| store_error(path, format!("failed to read destination: {error}")))?
        .map(|entry| {
            entry
                .map(|entry| PathBuf::from(entry.file_name()))
                .map_err(|error| {
                    store_error(path, format!("failed to read destination entry: {error}"))
                })
        })
        .collect()
}

/// Build all desired generated Rust files.
fn desired_files(snapshot: &ApiSnapshot) -> BTreeMap<String, Vec<u8>> {
    snapshot
        .crates()
        .iter()
        .map(|entry| {
            (
                entry.filename().to_string(),
                entry.contents().as_bytes().to_vec(),
            )
        })
        .collect()
}

/// Compare a validated complete tree byte-for-byte.
fn tree_is_identical(state: &TreeState, desired: &BTreeMap<String, Vec<u8>>) -> bool {
    !state.legacy_marker && state.unexpected.is_empty() && state.generated == *desired
}

/// Build one canonical typed comparison report.
fn report(
    current: &TreeState,
    desired: &BTreeMap<String, Vec<u8>>,
    skipped: &[String],
    interrupted: &[PathBuf],
) -> SnapshotReport {
    let mut changes = desired
        .iter()
        .map(|(name, bytes)| {
            let path = Path::new(name);
            let kind = if current.unexpected.iter().any(|entry| entry == path) {
                SnapshotChangeKind::Unexpected
            } else {
                match current.generated.get(name) {
                    Some(actual) if actual == bytes => SnapshotChangeKind::Unchanged,
                    Some(_) => SnapshotChangeKind::Changed,
                    None => SnapshotChangeKind::Added,
                }
            };
            SnapshotChange {
                path: path.to_path_buf(),
                kind,
            }
        })
        .collect::<Vec<_>>();
    let mut trailing = current
        .generated
        .keys()
        .filter(|name| !desired.contains_key(*name))
        .map(|name| SnapshotChange {
            path: PathBuf::from(name),
            kind: SnapshotChangeKind::Removed,
        })
        .collect::<Vec<_>>();
    if current.legacy_marker {
        trailing.push(SnapshotChange {
            path: PathBuf::from(LEGACY_MARKER_FILENAME),
            kind: SnapshotChangeKind::Removed,
        });
    }
    trailing.extend(
        current
            .unexpected
            .iter()
            .filter(|path| !desired.keys().any(|name| Path::new(name) == path.as_path()))
            .cloned()
            .map(|path| SnapshotChange {
                path,
                kind: SnapshotChangeKind::Unexpected,
            }),
    );
    trailing.sort_by(|left, right| left.path.cmp(&right.path));
    changes.extend(trailing);
    changes.extend(interrupted.iter().cloned().map(|path| SnapshotChange {
        path,
        kind: SnapshotChangeKind::Interrupted,
    }));
    SnapshotReport {
        changes,
        skipped_packages: skipped.to_vec(),
    }
}

/// Write and sync one complete sibling temporary tree.
fn write_complete_tree(destination: &Path, desired: &BTreeMap<String, Vec<u8>>) -> Result<TempDir> {
    let parent = destination.parent().expect("destination has parent");
    let temporary = Builder::new()
        .prefix(".ruskel-snapshot-new-")
        .tempdir_in(parent)
        .map_err(|error| {
            store_error(
                destination,
                format!("failed to create temporary tree: {error}"),
            )
        })?;
    for (name, bytes) in desired {
        let path = temporary.path().join(name);
        let mut file = File::create(&path).map_err(|error| {
            store_error(destination, format!("failed to create '{name}': {error}"))
        })?;
        file.write_all(bytes).map_err(|error| {
            store_error(destination, format!("failed to write '{name}': {error}"))
        })?;
        file.sync_all().map_err(|error| {
            store_error(destination, format!("failed to sync '{name}': {error}"))
        })?;
    }
    Ok(temporary)
}

/// Commit a complete temporary tree with filesystem renames.
fn commit_tree(destination: &Path, backup_prefix: &str, temporary: TempDir) -> Result<()> {
    commit_tree_with(destination, backup_prefix, temporary, |from, to| {
        fs::rename(from, to)
    })
}

/// Commit with an injectable rename operation for rollback proof.
fn commit_tree_with<R>(
    destination: &Path,
    backup_prefix: &str,
    temporary: TempDir,
    mut rename: R,
) -> Result<()>
where
    R: FnMut(&Path, &Path) -> IoResult<()>,
{
    let parent = destination.parent().expect("destination has parent");
    let backup_dir = Builder::new()
        .prefix(backup_prefix)
        .tempdir_in(parent)
        .map_err(|error| {
            store_error(
                destination,
                format!("failed to reserve backup path: {error}"),
            )
        })?;
    let backup = backup_dir.keep();
    fs::remove_dir(&backup).map_err(|error| {
        store_error(
            destination,
            format!("failed to prepare backup path: {error}"),
        )
    })?;
    let had_destination = destination.exists();
    if had_destination {
        rename(destination, &backup).map_err(|error| {
            store_error(
                destination,
                format!("failed to move old snapshot to backup: {error}"),
            )
        })?;
    }
    let new_tree = temporary.keep();
    if let Err(commit_error) = rename(&new_tree, destination) {
        if had_destination && let Err(restore_error) = rename(&backup, destination) {
            let cleanup = remove_validated_tree(&new_tree, destination);
            let message = match cleanup {
                Ok(()) => format!(
                    "failed to commit new snapshot: {commit_error}; rollback also failed: {restore_error}"
                ),
                Err(cleanup_error) => format!(
                    "failed to commit new snapshot: {commit_error}; rollback also failed: {restore_error}; temporary cleanup also failed: {cleanup_error}"
                ),
            };
            return Err(store_error(destination, message));
        }
        if let Err(cleanup_error) = remove_validated_tree(&new_tree, destination) {
            return Err(store_error(
                destination,
                format!(
                    "failed to commit new snapshot: {commit_error}; temporary cleanup also failed: {cleanup_error}"
                ),
            ));
        }
        return Err(store_error(
            destination,
            format!("failed to commit new snapshot: {commit_error}"),
        ));
    }
    if had_destination {
        remove_validated_tree(&backup, destination)?;
    }
    Ok(())
}

/// Remove only a complete tree whose files prove generated ownership.
fn remove_validated_tree(tree: &Path, destination: &Path) -> Result<()> {
    validate_tree(tree, false)?;
    fs::remove_dir_all(tree).map_err(|error| {
        store_error(
            destination,
            format!(
                "failed to remove validated backup '{}': {error}",
                tree.display()
            ),
        )
    })
}

/// Build a path-specific snapshot store error.
fn store_error(path: &Path, message: impl Into<String>) -> RuskelError {
    RuskelError::SnapshotStore {
        path: path.to_path_buf(),
        message: message.into(),
    }
}

#[cfg(test)]
mod tests {
    #[cfg(unix)]
    use std::os::unix::{fs::MetadataExt, fs::symlink};
    use std::{
        fs,
        io::Error,
        process,
        sync::atomic::{AtomicUsize, Ordering},
    };

    use super::*;
    use crate::snapshot::{CrateSnapshot, GENERATED_SOURCE_HEADER, SnapshotProfile};

    fn profile() -> SnapshotProfile {
        SnapshotProfile::fixture()
    }

    fn crate_snapshot(package: &str, crate_name: &str, body: &str) -> CrateSnapshot {
        CrateSnapshot {
            package: package.into(),
            crate_name: crate_name.into(),
            filename: format!("{package}.rs"),
            contents: format!(
                "{}pub mod {crate_name} {{\n    {body}\n}}\n",
                GENERATED_SOURCE_HEADER
            ),
        }
    }

    fn snapshot(crates: Vec<CrateSnapshot>) -> ApiSnapshot {
        ApiSnapshot {
            profile: profile(),
            crates,
            skipped_packages: vec!["tool".into()],
        }
    }

    #[test]
    fn update_is_bytewise_noop_and_removes_only_stale_managed_files() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        let first = snapshot(vec![
            crate_snapshot("alpha", "alpha", "pub fn one();"),
            crate_snapshot("beta", "beta", "pub fn two();"),
        ]);
        let report = SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&first)?;
        assert_eq!(report.changes()[0].kind(), SnapshotChangeKind::Added);
        assert_eq!(report.skipped_packages(), ["tool"]);
        assert_eq!(directory_entries(root.path())?, [PathBuf::from("api")]);

        let alpha = output.join("alpha.rs");
        let before_bytes = fs::read(&alpha)?;
        let before = fs::metadata(&alpha)?;
        let unchanged = SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&first)?;
        assert!(unchanged.is_current());
        let after = fs::metadata(&alpha)?;
        assert_eq!(fs::read(&alpha)?, before_bytes);
        assert_eq!(before.modified()?, after.modified()?);
        #[cfg(unix)]
        assert_eq!(before.ino(), after.ino());

        let second = snapshot(vec![crate_snapshot(
            "alpha",
            "alpha",
            "pub fn changed(value: u8);",
        )]);
        let changed = SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&second)?;
        assert!(changed.changes().iter().any(|change| {
            change.path() == Path::new("beta.rs") && change.kind() == SnapshotChangeKind::Removed
        }));
        assert!(!output.join("beta.rs").exists());
        Ok(())
    }

    #[test]
    fn check_classifies_drift_without_mutating_the_tree() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        let first = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn one();")]);
        SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&first)?;
        fs::write(output.join("notes.txt"), b"unowned\n")?;
        let before = fs::metadata(&output)?;
        let alpha = output.join("alpha.rs");
        let alpha_before = fs::read(&alpha)?;
        let alpha_metadata_before = fs::metadata(&alpha)?;

        let second = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn two();")]);
        let report = SnapshotStore::open(&output, SnapshotMode::Check)?.sync(&second)?;
        assert!(!report.is_current());
        assert!(report.changes().iter().any(|change| {
            change.path() == Path::new("alpha.rs") && change.kind() == SnapshotChangeKind::Changed
        }));
        assert!(report.changes().iter().any(|change| {
            change.path() == Path::new("notes.txt")
                && change.kind() == SnapshotChangeKind::Unexpected
        }));
        let after = fs::metadata(&output)?;
        let alpha_metadata_after = fs::metadata(&alpha)?;
        assert_eq!(fs::read(&alpha)?, alpha_before);
        assert_eq!(before.modified()?, after.modified()?);
        assert_eq!(before.len(), after.len());
        assert_eq!(
            alpha_metadata_before.modified()?,
            alpha_metadata_after.modified()?
        );
        assert_eq!(alpha_metadata_before.len(), alpha_metadata_after.len());
        #[cfg(unix)]
        {
            assert_eq!(before.ino(), after.ino());
            assert_eq!(alpha_metadata_before.ino(), alpha_metadata_after.ino());
        }
        assert!(SnapshotStore::open(&output, SnapshotMode::Update).is_err());
        assert_eq!(fs::read(output.join("notes.txt"))?, b"unowned\n");
        Ok(())
    }

    #[test]
    fn check_reports_missing_and_interrupted_backup_without_recovery() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        let captured = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn one();")]);
        SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&captured)?;
        fs::remove_file(output.join("alpha.rs"))?;
        let missing = SnapshotStore::open(&output, SnapshotMode::Check)?.sync(&captured)?;
        assert!(missing.changes().iter().any(|change| {
            change.path() == Path::new("alpha.rs") && change.kind() == SnapshotChangeKind::Added
        }));

        fs::write(
            output.join("alpha.rs"),
            captured.crates()[0].contents().as_bytes(),
        )?;
        let backup = root.path().join(".api.ruskel-snapshot-backup-fixture");
        fs::rename(&output, &backup)?;
        let store = SnapshotStore::open(&output, SnapshotMode::Check)?;
        let report = store.sync(&captured)?;
        assert!(report.changes().iter().any(|change| {
            change.path() == Path::new(".api.ruskel-snapshot-backup-fixture")
                && change.kind() == SnapshotChangeKind::Interrupted
        }));
        assert!(backup.exists());
        assert!(!output.exists());

        SnapshotStore::open(&output, SnapshotMode::Update)?;
        assert!(output.exists());
        assert!(!backup.exists());
        Ok(())
    }

    #[test]
    fn legacy_marker_is_removed_and_unowned_rust_is_rejected() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        fs::create_dir(&output)?;
        let captured = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn one();")]);
        fs::write(
            output.join(LEGACY_MARKER_FILENAME),
            format!("{LEGACY_MARKER_HEADER}\nformat = 99\n"),
        )?;
        fs::write(
            output.join("alpha.rs"),
            captured.crates()[0].contents().as_bytes(),
        )?;
        let check = SnapshotStore::open(&output, SnapshotMode::Check)?.sync(&captured)?;
        assert!(check.changes().iter().any(|change| {
            change.path() == Path::new(LEGACY_MARKER_FILENAME)
                && change.kind() == SnapshotChangeKind::Removed
        }));
        SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&captured)?;
        assert!(!output.join(LEGACY_MARKER_FILENAME).exists());

        fs::write(output.join("other.rs"), "// hand-written\n")?;
        let check = SnapshotStore::open(&output, SnapshotMode::Check)?.sync(&captured)?;
        assert!(check.changes().iter().any(|change| {
            change.path() == Path::new("other.rs")
                && change.kind() == SnapshotChangeKind::Unexpected
        }));
        assert!(SnapshotStore::open(&output, SnapshotMode::Update).is_err());
        Ok(())
    }

    #[cfg(unix)]
    #[test]
    fn destination_owned_symlinks_and_physical_aliases_are_safe() -> Result<()> {
        let root = tempfile::tempdir()?;
        let real_parent = root.path().join("real");
        fs::create_dir(&real_parent)?;
        let alias_parent = root.path().join("alias");
        symlink(&real_parent, &alias_parent)?;
        let direct = physical_identity(&real_parent.join("api"))?;
        let alias = physical_identity(&alias_parent.join("api"))?;
        assert_eq!(direct.0, alias.0);
        assert_eq!(direct.1, alias.1);
        if Path::new("/private/tmp").is_dir() {
            let name = format!("ruskel-physical-alias-{}", process::id());
            let short = physical_identity(&Path::new("/tmp").join(&name))?;
            let physical = physical_identity(&Path::new("/private/tmp").join(name))?;
            assert_eq!(short.0, physical.0);
            assert_eq!(short.1, physical.1);
        }

        let destination_link = root.path().join("api-link");
        symlink(real_parent.join("api"), &destination_link)?;
        assert!(SnapshotStore::open(&destination_link, SnapshotMode::Check).is_err());

        let output = real_parent.join("api");
        let captured = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn one();")]);
        SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&captured)?;
        fs::remove_file(output.join("alpha.rs"))?;
        symlink(root.path().join("outside"), output.join("alpha.rs"))?;
        let check = SnapshotStore::open(&output, SnapshotMode::Check)?.sync(&captured)?;
        assert!(check.changes().iter().any(|change| {
            change.path() == Path::new("alpha.rs")
                && change.kind() == SnapshotChangeKind::Unexpected
        }));
        assert!(SnapshotStore::open(&output, SnapshotMode::Update).is_err());
        Ok(())
    }

    #[test]
    fn failed_second_rename_restores_old_tree_and_cleans_new_tree() -> Result<()> {
        let root = tempfile::tempdir()?;
        let output = root.path().join("api");
        let old = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn one();")]);
        SnapshotStore::open(&output, SnapshotMode::Update)?.sync(&old)?;
        let desired_snapshot = snapshot(vec![crate_snapshot("alpha", "alpha", "pub fn two();")]);
        let desired = desired_files(&desired_snapshot);
        let temporary = write_complete_tree(&output, &desired)?;
        let calls = AtomicUsize::new(0);
        let result = commit_tree_with(
            &output,
            ".api.ruskel-snapshot-backup-",
            temporary,
            |from, to| {
                if calls.fetch_add(1, Ordering::SeqCst) == 1 {
                    Err(Error::other("injected commit failure"))
                } else {
                    fs::rename(from, to)
                }
            },
        );
        assert!(result.is_err());
        assert_eq!(
            fs::read(output.join("alpha.rs"))?,
            old.crates()[0].contents().as_bytes()
        );
        assert!(find_backups(&output, ".api.ruskel-snapshot-backup-")?.is_empty());
        assert!(fs::read_dir(root.path())?.all(|entry| {
            !entry
                .expect("entry")
                .file_name()
                .to_string_lossy()
                .starts_with(".ruskel-snapshot-new-")
        }));
        Ok(())
    }
}
