// @generated by `ruskel-snapshot`; do not edit.

pub mod libruskel {
    //! Ruskel generates skeletonized versions of Rust crates.
    //!
    //! It produces a single-page, syntactically valid Rust code representation of a
    //! crate, with all implementations omitted. This provides a clear overview of
    //! the crate's structure and public API.
    //!
    //! Ruskel works by first fetching all dependencies, then using the nightly Rust
    //! toolchain to generate JSON documentation data. This data is then parsed and
    //! rendered into the skeletonized format. The skeletonized code is then
    //! formatted with rustfmt, and optionally has syntax highlighting applied.
    //!
    //!
    //! You must have the nightly Rust toolchain installed to use (but not to
    //! install) Ruskel.
    //!
    //! Canonical workspace snapshots are captured separately through
    //! [`Ruskel::capture_snapshot`]. Capture returns an in-memory [`ApiSnapshot`]
    //! and never writes a destination directory.

    pub mod highlight {
        //! Syntax highlighting functionality for Rust code.

        /// Applies syntax highlighting to Rust code using the Solarized (dark) theme.
        ///
        /// # Arguments
        /// * `code` - The Rust code to highlight
        ///
        /// # Returns
        /// A string with ANSI escape codes for terminal color output
        pub fn highlight_code(code: &str) -> crate::Result<String> {}
    }

    pub mod toolchain {
        //! Shared nightly/rustup helpers.
        //! Shared nightly and `rustup` helpers.

        /// Return the active portable dated-nightly toolchain name.
        pub fn active_dated_nightly() -> crate::error::Result<String> {}

        /// Ensure the nightly toolchain exists and report whether the `rust-docs-json`
        /// component is installed.
        pub fn ensure_nightly_with_docs() -> crate::error::Result<bool> {}

        /// Return the host target reported by the selected compiler.
        pub fn host_target(toolchain: &str) -> crate::error::Result<String> {}

        /// Locate the nightly toolchain sysroot path.
        pub fn nightly_sysroot() -> crate::error::Result<std::path::PathBuf> {}

        /// Locate a binary installed for the selected toolchain.
        pub fn toolchain_binary(
            toolchain: &str,
            binary: &str,
        ) -> crate::error::Result<std::path::PathBuf> {
        }

        /// Return the SHA-256 identity of one compiler description.
        pub fn toolchain_identity(toolchain: &str) -> crate::error::Result<String> {}
    }

    /// Complete ordered snapshot captured without destination I/O.
    pub struct ApiSnapshot {}

    /// A cache entry or operation that Ruskel skipped.
    pub struct CacheIssue {}

    /// A read-only snapshot of the dedicated Ruskel cache.
    pub struct CacheStatus {}

    /// Result of one explicit cache-clean operation.
    pub struct CleanReport {}

    /// Cargo feature and visibility options for one crate inspection request.
    pub struct CrateRequest {
        /// Build without the crate's default features.
        pub no_default_features: bool,
        /// Build with every optional feature.
        pub all_features: bool,
        /// Explicit features to enable.
        pub features: Vec<String>,
        /// Include private and crate-private items.
        pub private_items: bool,
    }

    /// One canonical generated crate file held in memory.
    pub struct CrateSnapshot {}

    /// Binary target metadata for frontmatter rendering.
    pub struct FrontmatterBinaryTarget {}

    /// Configuration describing optional frontmatter comments rendered ahead of
    /// skeleton output.
    pub struct FrontmatterConfig {}

    /// Individual search hit included in the frontmatter summary.
    pub struct FrontmatterHit {}

    /// Summary of a search invocation attached to the frontmatter.
    pub struct FrontmatterSearch {}

    /// Lightweight record describing an item for list mode output.
    pub struct ListItem {
        /// Kind classification for the item.
        pub kind: SearchItemKind,
        /// Canonical path rendered as a `::` separated string.
        pub path: String,
    }

    /// Configurable renderer that turns rustdoc data into skeleton Rust source.
    pub struct Renderer {}

    /// Convenience alias for results returned by libruskel operations.
    pub type Result<T> = result::Result<T, RuskelError>;

    /// Ruskel generates a skeletonized version of a Rust crate in a single page.
    /// It produces syntactically valid Rust code with all implementations omitted.
    ///
    /// The tool performs a 'cargo fetch' to ensure all referenced code is available
    /// locally, then uses 'cargo doc' with the nightly toolchain to generate JSON
    /// output. This JSON is parsed and used to render the skeletonized code. Users
    /// must have the nightly Rust toolchain installed and available.
    pub struct Ruskel {}

    /// Errors surfaced while generating rustdoc skeletons.
    pub enum RuskelError {
        #[error("Invalid snapshot profile: {0}")]
        /// Indicates that a snapshot profile is invalid or unavailable.
        SnapshotProfile(String),
        #[error("Snapshot discovery failed for '{}': {message}", input.display())]
        /// Indicates that an input could not be discovered as a snapshot package.
        SnapshotDiscovery {
            /// Input path associated with the failure.
            input: std::path::PathBuf,
            /// Actionable discovery failure.
            message: String,
        },
        #[error("Snapshot capture failed for package '{package}': {message}")]
        /// Indicates that rustdoc generation failed for a selected package.
        SnapshotCapture {
            /// Selected Cargo package.
            package: String,
            /// Underlying build failure.
            message: String,
        },
        #[error("Snapshot rendering failed for package '{package}': {message}")]
        /// Indicates that strict snapshot rendering rejected a public surface.
        SnapshotRender {
            /// Selected Cargo package.
            package: String,
            /// Underlying fidelity or formatting failure.
            message: String,
        },
        #[error("Snapshot store failed for '{}': {message}", path.display())]
        /// Indicates that snapshot persistence failed for a destination path.
        SnapshotStore {
            /// Destination path associated with the failure.
            path: std::path::PathBuf,
            /// Actionable persistence failure.
            message: String,
        },
        #[error("Module not found: {0}")]
        /// Indicates that a specified module could not be found.
        ModuleNotFound(String),
        #[error("Failed to read file: {0}")]
        /// Indicates a failure in reading a file, wrapping the underlying IO error.
        FileRead(io::Error),
        #[error("Cache {action} failed for '{}': {source}", path.display())]
        /// Indicates an I/O failure in a cache-owned path.
        CacheIo {
            /// Operation that failed.
            action: &'static str,
            /// Cache-owned path associated with the failure.
            path: std::path::PathBuf,
            #[source]
            /// Underlying filesystem error.
            source: io::Error,
        },
        #[error("Invalid Ruskel cache at '{}': {message}", path.display())]
        /// Indicates that a cache root or entry has an invalid layout.
        CacheLayout {
            /// Path that failed validation.
            path: std::path::PathBuf,
            /// Actionable validation failure.
            message: String,
        },
        #[error("{0}")]
        /// Indicates a failure in the code generation process.
        Generate(String),
        #[error("Item not found in rustdoc index: {0}")]
        /// Indicates an item referenced by rustdoc output could not be found.
        ItemNotFound(String),
        #[error("Cargo error: {0}")]
        /// Indicates an error occurred while executing a Cargo command.
        Cargo(String),
        #[error("Formatting error: {0}")]
        /// Indicates an error occurred during code formatting.
        Format(String),
        #[error("Highlighting error: {0}")]
        /// Indicates an error occurred during syntax highlighting.
        Highlight(String),
        #[error("Filter '{0}' did not match any items")]
        /// The specified filter did not match any items.
        FilterNotMatched(String),
        #[error("Failed to parse Cargo.toml manifest: {0}")]
        /// Failed to parse a Cargo.toml manifest
        ManifestParse(String),
        #[error("Failed to find Cargo.toml in the current directory or any parent directories")]
        /// Indicates that the Cargo.toml manifest file could not be found in the
        /// current directory or any parent directories.
        ManifestNotFound,
        #[error("Invalid version: {0}")]
        /// Indicates an invalid version string was provided.
        InvalidVersion(String),
        #[error("Invalid target: {0}")]
        /// Indicates an invalid target specification was provided.
        InvalidTarget(String),
        #[error("No matching package")]
        /// Indicates a dependency was not found in the registry.
        DependencyNotFound,
    }

    /// Domains that a search query can operate over.
    pub struct SearchDomain(_);

    /// Classified kind associated with a search result.
    pub enum SearchItemKind {
        /// Synthetic crate root module.
        Crate,
        /// Regular module.
        Module,
        /// Struct definition.
        Struct,
        /// Union definition.
        Union,
        /// Enum definition.
        Enum,
        /// Variant within an enum.
        EnumVariant,
        /// Named or positional field within a struct or union.
        Field,
        /// Trait definition.
        Trait,
        /// Trait alias definition.
        TraitAlias,
        /// Free function.
        Function,
        /// Method inside an impl block.
        Method,
        /// Trait method declaration.
        TraitMethod,
        /// Associated constant.
        AssocConst,
        /// Associated type.
        AssocType,
        /// Top-level constant.
        Constant,
        /// Static item.
        Static,
        /// Type alias.
        TypeAlias,
        /// `use` declaration.
        Use,
        /// Macro_rules! definition.
        Macro,
        /// Procedural macro entrypoint.
        ProcMacro,
        /// Primitive type description.
        Primitive,
        /// Synthetic segment representing an impl target.
        ImplTarget,
    }

    /// Options that control how a crate search should be performed.
    pub struct SearchOptions {
        /// Raw user query to evaluate.
        pub query: String,
        /// Domains to search across; defaults to [`SearchDomain::default`].
        pub domains: SearchDomain,
        /// Whether matching should respect letter casing.
        pub case_sensitive: bool,
        /// Whether matched container items should expand to include their children.
        pub expand_containers: bool,
    }

    /// Component in a canonical path leading to an item.
    pub struct SearchPathSegment {
        /// Raw identifier for the segment without keyword escaping.
        pub name: String,
        /// Display name used when rendering the path.
        pub display_name: String,
        /// Classification of the segment.
        pub kind: SearchItemKind,
        /// Whether the segment corresponds to a publicly visible item.
        pub is_public: bool,
    }

    /// Aggregated search response containing matches and rendered output.
    pub struct SearchResponse {
        /// Matched records returned by the query.
        pub results: Vec<SearchResult>,
        /// Rendered skeleton filtered to only include matched items.
        pub rendered: String,
    }

    /// Result of performing a query against a crate index.
    pub struct SearchResult {
        /// Identifier of the matching item.
        pub item_id: rustdoc_types::Id,
        /// Kind of result item.
        pub kind: SearchItemKind,
        /// Canonical path segments to reach the item.
        pub path: Vec<SearchPathSegment>,
        /// Canonical path rendered as a `::` separated string.
        pub path_string: String,
        /// Raw identifier of the item.
        pub raw_name: String,
        /// Display name formatted for rendering.
        pub display_name: String,
        /// Documentation snippet if available.
        pub docs: Option<String>,
        /// Rendered signature used for matching and display.
        pub signature: Option<String>,
        /// Ancestor chain of items that must be rendered for context.
        pub ancestors: Vec<rustdoc_types::Id>,
        /// Domains that produced a match for this query result.
        pub matched: SearchDomain,
    }

    /// One path and its typed comparison result.
    pub struct SnapshotChange {}

    /// One typed snapshot comparison result.
    pub enum SnapshotChangeKind {
        /// The captured entry does not exist in the stored tree.
        Added,
        /// The captured and stored entry bytes differ.
        Changed,
        /// A previously managed entry is no longer captured.
        Removed,
        /// The captured and stored entry bytes are identical.
        Unchanged,
        /// The destination contains an entry that Ruskel does not own.
        Unexpected,
        /// A bounded backup shows an interrupted directory swap.
        Interrupted,
    }

    /// Cargo feature policy shared by every crate in one snapshot.
    pub struct SnapshotFeatures {}

    /// Persistence behavior for one snapshot destination.
    pub enum SnapshotMode {
        /// Replace the generated tree when captured bytes differ.
        Update,
        /// Compare captured bytes without changing the generated tree.
        Check,
    }

    /// Fully resolved capture profile for one invocation.
    pub struct SnapshotProfile {}

    /// Optional capture profile overrides.
    pub struct SnapshotProfileOptions {}

    /// Complete ordered result from one snapshot synchronization.
    pub struct SnapshotReport {}

    /// Inputs and resolved profile for one in-memory capture.
    pub struct SnapshotRequest {}

    /// One physically resolved snapshot destination.
    pub struct SnapshotStore {}

    /// Status for one nightly toolchain entry in the cache.
    pub struct ToolchainCacheStatus {}

    /// Status for one workspace entry in the cache.
    pub struct WorkspaceCacheStatus {}

    impl ApiSnapshot {
        /// Return binary-only package names in canonical order.
        pub fn skipped_packages(&self) -> &[String] {}

        /// Return generated crate files in canonical package order.
        pub fn crates(&self) -> &[CrateSnapshot] {}

        /// Return the canonical profile used for this capture.
        pub fn profile(&self) -> &SnapshotProfile {}
    }

    impl Clone for ApiSnapshot {
        fn clone(&self) -> ApiSnapshot {}
    }

    impl Debug for ApiSnapshot {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ApiSnapshot {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ApiSnapshot {
        fn eq(&self, other: &ApiSnapshot) -> bool {}
    }

    impl Binary for SearchDomain {
        fn fmt(&self, f: &mut __private::core::fmt::Formatter<'_>) -> __private::core::fmt::Result {
        }
    }

    impl BitAnd for SearchDomain {
        /// The bitwise and (`&`) of the bits in `self` and `other`.
        fn bitand(self, other: Self) -> Self {}

        type Output = SearchDomain;
    }

    impl BitAndAssign for SearchDomain {
        /// The bitwise and (`&`) of the bits in `self` and `other`.
        fn bitand_assign(&mut self, other: Self) {}
    }

    impl BitOr for SearchDomain {
        /// The bitwise or (`|`) of the bits in `self` and `other`.
        fn bitor(self, other: SearchDomain) -> Self {}

        type Output = SearchDomain;
    }

    impl BitOrAssign for SearchDomain {
        /// The bitwise or (`|`) of the bits in `self` and `other`.
        fn bitor_assign(&mut self, other: Self) {}
    }

    impl BitXor for SearchDomain {
        /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
        fn bitxor(self, other: Self) -> Self {}

        type Output = SearchDomain;
    }

    impl BitXorAssign for SearchDomain {
        /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
        fn bitxor_assign(&mut self, other: Self) {}
    }

    impl Clone for SearchDomain {
        fn clone(&self) -> SearchDomain {}
    }

    impl Debug for SearchDomain {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for SearchDomain {
        fn default() -> Self {}
    }

    impl Eq for SearchDomain {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Extend<SearchDomain> for SearchDomain {
        /// The bitwise or (`|`) of the bits in each flags value.
        fn extend<T: __private::core::iter::IntoIterator<Item = Self>>(&mut self, iterator: T) {}
    }

    impl Flags for SearchDomain {
        const FLAGS: &'static [Flag<SearchDomain>] = _;
        fn all_named() -> SearchDomain {}

        fn bits(&self) -> u32 {}

        fn from_bits_retain(bits: u32) -> SearchDomain {}

        type Bits = u32;
    }

    impl FromIterator<SearchDomain> for SearchDomain {
        /// The bitwise or (`|`) of the bits in each flags value.
        fn from_iter<T: __private::core::iter::IntoIterator<Item = Self>>(iterator: T) -> Self {}
    }

    impl IntoIterator for SearchDomain {
        fn into_iter(self) -> Self::IntoIter {}

        type IntoIter = Iter<SearchDomain>;
        type Item = SearchDomain;
    }

    impl LowerHex for SearchDomain {
        fn fmt(&self, f: &mut __private::core::fmt::Formatter<'_>) -> __private::core::fmt::Result {
        }
    }

    impl Not for SearchDomain {
        /// The bitwise negation (`!`) of the bits in `self`, truncating the result.
        fn not(self) -> Self {}

        type Output = SearchDomain;
    }

    impl Octal for SearchDomain {
        fn fmt(&self, f: &mut __private::core::fmt::Formatter<'_>) -> __private::core::fmt::Result {
        }
    }

    impl PartialEq for SearchDomain {
        fn eq(&self, other: &SearchDomain) -> bool {}
    }

    impl PublicFlags for SearchDomain {
        type Internal = InternalBitFlags;
        type Primitive = u32;
    }

    impl SearchDomain {
        /// Match against canonical module paths.
        pub const PATHS: Self = _;
        /// Match against documentation strings.
        pub const DOCS: Self = _;
        /// Match against item names.
        pub const NAMES: Self = _;
        /// Match against rendered item signatures.
        pub const SIGNATURES: Self = _;
        #[must_use]
        /// The bitwise and (`&`) of the bits in `self` and `other`.
        pub const fn intersection(self, other: Self) -> Self {}

        #[must_use]
        /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
        pub const fn symmetric_difference(self, other: Self) -> Self {}

        #[must_use]
        /// The bitwise negation (`!`) of the bits in `self`, truncating the result.
        pub const fn complement(self) -> Self {}

        #[must_use]
        /// The bitwise or (`|`) of the bits in `self` and `other`.
        pub const fn r#union(self, other: Self) -> Self {}

        #[must_use]
        /// The intersection of `self` with the complement of `other` (`&!`).
        ///
        /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
        /// `difference` won't truncate `other`, but the `!` operator will.
        pub const fn difference(self, other: Self) -> Self {}

        /// Call `insert` when `value` is `true` or `remove` when `value` is `false`.
        pub fn set(&mut self, other: Self, value: bool) {}

        /// Convert from a bits value exactly.
        pub const fn from_bits_retain(bits: u32) -> Self {}

        /// Convert from a bits value, unsetting any unknown bits.
        pub const fn from_bits_truncate(bits: u32) -> Self {}

        /// Convert from a bits value.
        ///
        /// This method will return `None` if any unknown bits are set.
        pub const fn from_bits(bits: u32) -> __private::core::option::Option<Self> {}

        /// Get a flags value with all bits unset.
        pub const fn empty() -> Self {}

        /// Get a flags value with all known bits set.
        pub const fn all() -> Self {}

        /// Get a flags value with the bits of a flag with the given name set.
        ///
        /// This method will return `None` if `name` is empty or doesn't
        /// correspond to any named flag.
        pub fn from_name(name: &str) -> __private::core::option::Option<Self> {}

        /// Get the underlying bits value.
        ///
        /// The returned value is exactly the bits set in this flags value.
        pub const fn bits(&self) -> u32 {}

        /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
        pub fn toggle(&mut self, other: Self) {}

        /// The bitwise or (`|`) of the bits in `self` and `other`.
        pub fn insert(&mut self, other: Self) {}

        /// The intersection of `self` with the complement of `other` (`&!`).
        ///
        /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
        /// `remove` won't truncate `other`, but the `!` operator will.
        pub fn remove(&mut self, other: Self) {}

        /// Whether all bits in `self` are unset.
        pub const fn is_empty(&self) -> bool {}

        /// Whether all known bits in this flags value are set.
        pub const fn is_all(&self) -> bool {}

        /// Whether all set bits in `other` are also set in `self`.
        pub const fn contains(&self, other: Self) -> bool {}

        /// Whether any set bits in `other` are also set in `self`.
        pub const fn intersects(&self, other: Self) -> bool {}

        /// Yield a set of contained flags values.
        ///
        /// Each yielded flags value will correspond to a defined named flag. Any unknown bits
        /// will be yielded together as a final flags value.
        pub const fn iter(&self) -> iter::Iter<SearchDomain> {}

        /// Yield a set of contained named flags values.
        ///
        /// This method is like [`iter`](#method.iter), except only yields bits in contained named flags.
        /// Any unknown bits, or bits not corresponding to a contained flag will not be yielded.
        pub const fn iter_names(&self) -> iter::IterNames<SearchDomain> {}

        /// Parse one case-insensitive search-domain token.
        pub fn parse(token: &str) -> Result<Self, String> {}

        /// Return human-friendly labels for every selected domain.
        pub fn labels(self) -> Vec<&'static str> {}
    }

    impl Sub for SearchDomain {
        /// The intersection of `self` with the complement of `other` (`&!`).
        ///
        /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
        /// `difference` won't truncate `other`, but the `!` operator will.
        fn sub(self, other: Self) -> Self {}

        type Output = SearchDomain;
    }

    impl SubAssign for SearchDomain {
        /// The intersection of `self` with the complement of `other` (`&!`).
        ///
        /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
        /// `difference` won't truncate `other`, but the `!` operator will.
        fn sub_assign(&mut self, other: Self) {}
    }

    impl UpperHex for SearchDomain {
        fn fmt(&self, f: &mut __private::core::fmt::Formatter<'_>) -> __private::core::fmt::Result {
        }
    }

    impl CacheIssue {
        /// Return an actionable description of the issue.
        pub fn message(&self) -> &str {}

        /// Return the affected path.
        pub fn path(&self) -> &Path {}
    }

    impl Clone for CacheIssue {
        fn clone(&self) -> CacheIssue {}
    }

    impl Debug for CacheIssue {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for CacheIssue {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for CacheIssue {
        fn eq(&self, other: &CacheIssue) -> bool {}
    }

    impl CacheStatus {
        /// Return entries that status could not safely recognize or inspect.
        pub fn skipped(&self) -> &[CacheIssue] {}

        /// Return recognized toolchain entries in identity order.
        pub fn toolchains(&self) -> &[ToolchainCacheStatus] {}

        /// Return recognized trash usage in bytes.
        pub fn trash_bytes(&self) -> u64 {}

        /// Return the canonical cache root.
        pub fn root(&self) -> &Path {}

        /// Return total recognized build and trash usage in bytes.
        pub fn total_bytes(&self) -> u64 {}

        /// Return usage above the soft high-water mark.
        pub fn excess_bytes(&self) -> u64 {}
    }

    impl Clone for CacheStatus {
        fn clone(&self) -> CacheStatus {}
    }

    impl Debug for CacheStatus {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl CleanReport {
        /// Return recognized usage after the clean.
        pub fn usage_after(&self) -> u64 {}

        /// Return removal failures.
        pub fn failures(&self) -> &[CacheIssue] {}

        /// Return the canonical cache root.
        pub fn root(&self) -> &Path {}

        /// Return the number of removed toolchain and trash entries.
        pub fn removed_entries(&self) -> u64 {}

        /// Return the recognized bytes removed by this operation.
        pub fn removed_bytes(&self) -> u64 {}

        /// Return unrecognized entries that the clean preserved.
        pub fn skipped(&self) -> &[CacheIssue] {}

        /// Return whether an active request prevented the clean.
        pub fn root_busy(&self) -> bool {}

        /// Return whether the clean removed all safe entries without contention or
        /// failure.
        pub fn is_complete(&self) -> bool {}
    }

    impl Clone for CleanReport {
        fn clone(&self) -> CleanReport {}
    }

    impl Debug for CleanReport {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Clone for CrateRequest {
        fn clone(&self) -> CrateRequest {}
    }

    impl Debug for CrateRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for CrateRequest {
        fn default() -> CrateRequest {}
    }

    impl Eq for CrateRequest {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for CrateRequest {
        fn eq(&self, other: &CrateRequest) -> bool {}
    }

    impl Clone for CrateSnapshot {
        fn clone(&self) -> CrateSnapshot {}
    }

    impl CrateSnapshot {
        /// Return the Cargo package name.
        pub fn package(&self) -> &str {}

        /// Return the Rust library crate name.
        pub fn crate_name(&self) -> &str {}

        /// Return the complete generated Rust source.
        pub fn contents(&self) -> &str {}

        /// Return the generated filename relative to the snapshot root.
        pub fn filename(&self) -> &str {}
    }

    impl Debug for CrateSnapshot {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for CrateSnapshot {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for CrateSnapshot {
        fn eq(&self, other: &CrateSnapshot) -> bool {}
    }

    impl Clone for FrontmatterBinaryTarget {
        fn clone(&self) -> FrontmatterBinaryTarget {}
    }

    impl Debug for FrontmatterBinaryTarget {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl FrontmatterBinaryTarget {
        /// Build a binary target descriptor for frontmatter output.
        pub fn new(name: impl Into<String>, is_bin_only: bool) -> Self {}
    }

    impl Clone for FrontmatterConfig {
        fn clone(&self) -> FrontmatterConfig {}
    }

    impl Debug for FrontmatterConfig {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for FrontmatterConfig {
        fn default() -> FrontmatterConfig {}
    }

    impl FrontmatterConfig {
        /// Attach binary target metadata to the frontmatter.
        pub fn with_binary_target(self, binary_target: FrontmatterBinaryTarget) -> Self {}

        /// Attach search metadata summarising the invocation.
        pub fn with_search(self, search: FrontmatterSearch) -> Self {}

        /// Attach the resolved filter path used for rendering.
        pub fn with_filter(self, filter: Option<String>) -> Self {}

        /// Create a configuration with frontmatter enabled for the provided target
        /// specification.
        pub fn for_target(target: impl Into<String>) -> Self {}

        /// Disable frontmatter rendering entirely.
        pub fn disabled() -> Self {}

        /// Render the configured frontmatter when enabled, returning the formatted
        /// comment block.
        pub fn render(
            &self,
            include_private: bool,
            render_auto_impls: bool,
            render_blanket_impls: bool,
        ) -> Option<String> {
        }
    }

    impl Clone for FrontmatterHit {
        fn clone(&self) -> FrontmatterHit {}
    }

    impl Debug for FrontmatterHit {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl FrontmatterHit {
        /// Build a frontmatter search hit summary.
        pub fn new(path: impl Into<String>, domains: SearchDomain) -> Self {}
    }

    impl Clone for FrontmatterSearch {
        fn clone(&self) -> FrontmatterSearch {}
    }

    impl Debug for FrontmatterSearch {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl FrontmatterSearch {
        /// Build a search summary for frontmatter output.
        pub fn new(
            query: impl Into<String>,
            domains: SearchDomain,
            case_sensitive: bool,
            expand_containers: bool,
            hits: Vec<FrontmatterHit>,
        ) -> Self {
        }
    }

    impl Clone for ListItem {
        fn clone(&self) -> ListItem {}
    }

    impl Debug for ListItem {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ListItem {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ListItem {
        fn eq(&self, other: &ListItem) -> bool {}
    }

    impl Clone for Ruskel {
        fn clone(&self) -> Ruskel {}
    }

    impl Debug for Ruskel {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Ruskel {
        fn default() -> Self {}
    }

    impl Ruskel {
        /// Capture canonical public APIs for local Cargo inputs entirely in memory.
        ///
        /// Snapshot capture uses this instance's cache, offline, and silent
        /// settings. Interactive rendering options do not affect the artifact.
        pub fn capture_snapshot(&self, request: &SnapshotRequest) -> Result<ApiSnapshot> {}

        /// Creates a new Ruskel instance with default configuration.
        ///
        /// # Target Format
        ///
        /// A target specification is an entrypoint, followed by an optional path,
        /// with components separated by '::'.
        ///
        ///   entrypoint::path
        ///
        /// An entrypoint can be:
        ///
        /// - A path to a Rust file
        /// - A directory containing a Cargo.toml file
        /// - A module name
        /// - A package name. In this case the name can also include a version
        ///   number, separated by an '@' symbol.
        ///
        /// Ruskel selects workspace members before direct dependencies. It matches
        /// a direct dependency by its `Cargo.toml` key. If neither exists, it
        /// resolves the name through the configured Cargo registry. The path
        /// after the first `::` stays inside the selected entrypoint.
        ///
        /// # Examples of valid targets:
        ///
        /// - src/lib.rs
        /// - my_module
        /// - serde
        /// - rustdoc-types
        /// - serde::Deserialize
        /// - serde@1.0
        /// - rustdoc-types::Crate
        /// - rustdoc_types::Crate
        pub fn new() -> Self {}

        /// Enables or disables frontmatter emission on rendered output.
        pub fn with_frontmatter(self, frontmatter: bool) -> Self {}

        /// Enables or disables offline mode, which prevents Ruskel from fetching
        /// dependencies from the network.
        pub fn with_offline(self, offline: bool) -> Self {}

        /// Enables or disables rendering of auto-implemented traits.
        pub fn with_auto_impls(self, auto_impls: bool) -> Self {}

        /// Enables or disables silent mode, which suppresses output during
        /// processing.
        pub fn with_silent(self, silent: bool) -> Self {}

        /// Execute a search against the crate and return the matched items along
        /// with a rendered skeleton.
        ///
        /// The search respects the same target resolution logic as
        /// [`Self::render`], but only the matched items and their ancestors are
        /// emitted in the final skeleton.
        pub fn search(
            &self,
            target: &str,
            request: &CrateRequest,
            options: &SearchOptions,
        ) -> Result<SearchResponse> {
        }

        /// Override the dedicated cache root.
        ///
        /// Pass `None` to restore `RUSKEL_CACHE_DIR` and platform cache resolution.
        pub fn with_cache_dir(self, dir: Option<PathBuf>) -> Self {}

        /// Overrides the binary target used when rendering a crate.
        pub fn with_bin_target(self, bin_target: Option<String>) -> Self {}

        /// Produce a lightweight listing of crate items, optionally filtered by a
        /// search query.
        pub fn list(
            &self,
            target: &str,
            request: &CrateRequest,
            search: Option<&SearchOptions>,
        ) -> Result<Vec<ListItem>> {
        }

        /// Remove cache-owned build data when no request is active.
        pub fn clean_cache(&self) -> Result<CleanReport> {}

        /// Render the crate target into a Rust skeleton without filtering.
        pub fn render(&self, target: &str, request: &CrateRequest) -> Result<String> {}

        /// Return a read-only snapshot of the dedicated cache.
        pub fn cache_status(&self) -> Result<CacheStatus> {}

        /// Returns a pretty-printed version of the crate's JSON representation.
        ///
        /// # Arguments
        /// * `target` - The target specification (see new() documentation for
        ///   format)
        /// * `request` - Cargo feature and visibility options
        pub fn raw_json(&self, target: &str, request: &CrateRequest) -> Result<String> {}

        /// Returns the parsed representation of the crate's API.
        ///
        /// # Arguments
        /// * `target` - The target specification (see new() documentation for
        ///   format)
        /// * `request` - Cargo feature and visibility options
        pub fn inspect(&self, target: &str, request: &CrateRequest) -> Result<Crate> {}
    }

    impl Clone for SearchItemKind {
        fn clone(&self) -> SearchItemKind {}
    }

    impl Debug for SearchItemKind {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SearchItemKind {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for SearchItemKind {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for SearchItemKind {
        fn eq(&self, other: &SearchItemKind) -> bool {}
    }

    impl SearchItemKind {
        /// Human-friendly label describing the item kind.
        pub fn label(self) -> &'static str {}
    }

    impl Clone for SearchOptions {
        fn clone(&self) -> SearchOptions {}
    }

    impl Debug for SearchOptions {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl SearchOptions {
        /// Create a new options struct with the provided query string.
        pub fn new(query: impl Into<String>) -> Self {}

        /// Create fully-specified search options with transport-independent
        /// defaults.
        pub fn configured(
            query: impl Into<String>,
            domains: SearchDomain,
            case_sensitive: bool,
            expand_containers: bool,
        ) -> Self {
        }

        /// Ensure the options have at least one domain selected.
        pub fn ensure_domains(&mut self) {}
    }

    impl Clone for SearchPathSegment {
        fn clone(&self) -> SearchPathSegment {}
    }

    impl Debug for SearchPathSegment {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SearchPathSegment {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SearchPathSegment {
        fn eq(&self, other: &SearchPathSegment) -> bool {}
    }

    impl Clone for SearchResponse {
        fn clone(&self) -> SearchResponse {}
    }

    impl Debug for SearchResponse {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Clone for SearchResult {
        fn clone(&self) -> SearchResult {}
    }

    impl Debug for SearchResult {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Clone for SnapshotChange {
        fn clone(&self) -> SnapshotChange {}
    }

    impl Debug for SnapshotChange {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotChange {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotChange {
        fn eq(&self, other: &SnapshotChange) -> bool {}
    }

    impl SnapshotChange {
        /// Return the comparison result.
        pub fn kind(&self) -> SnapshotChangeKind {}

        /// Return the path relative to the snapshot parent.
        pub fn path(&self) -> &Path {}
    }

    impl Clone for SnapshotChangeKind {
        fn clone(&self) -> SnapshotChangeKind {}
    }

    impl Debug for SnapshotChangeKind {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotChangeKind {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotChangeKind {
        fn eq(&self, other: &SnapshotChangeKind) -> bool {}
    }

    impl Clone for SnapshotFeatures {
        fn clone(&self) -> SnapshotFeatures {}
    }

    impl Debug for SnapshotFeatures {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for SnapshotFeatures {
        fn default() -> Self {}
    }

    impl Eq for SnapshotFeatures {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotFeatures {
        fn eq(&self, other: &SnapshotFeatures) -> bool {}
    }

    impl SnapshotFeatures {
        /// Return the sorted selected feature list.
        pub fn features(&self) -> &[String] {}

        /// Return whether Cargo enables each package's default features.
        pub fn default_features(&self) -> bool {}

        /// Return whether Cargo enables every feature.
        pub fn all_features(&self) -> bool {}

        /// Validate and canonicalize one snapshot feature policy.
        pub fn new(
            default_features: bool,
            all_features: bool,
            features: Vec<String>,
        ) -> Result<Self> {
        }
    }

    impl Clone for SnapshotMode {
        fn clone(&self) -> SnapshotMode {}
    }

    impl Debug for SnapshotMode {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotMode {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotMode {
        fn eq(&self, other: &SnapshotMode) -> bool {}
    }

    impl Clone for SnapshotProfile {
        fn clone(&self) -> SnapshotProfile {}
    }

    impl Debug for SnapshotProfile {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotProfile {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotProfile {
        fn eq(&self, other: &SnapshotProfile) -> bool {}
    }

    impl SnapshotProfile {
        /// Resolve explicit overrides and invocation defaults as one profile.
        pub fn resolve(options: SnapshotProfileOptions) -> Result<Self> {}

        /// Return the selected Cargo target triple.
        pub fn target(&self) -> &str {}

        /// Return the selected nightly toolchain.
        pub fn toolchain(&self) -> &str {}

        /// Return the shared Cargo feature policy.
        pub fn features(&self) -> &SnapshotFeatures {}

        /// Validate a complete profile against the local Rust installation.
        pub fn new(
            toolchain: impl Into<String>,
            target: impl Into<String>,
            features: SnapshotFeatures,
        ) -> Result<Self> {
        }
    }

    impl Clone for SnapshotProfileOptions {
        fn clone(&self) -> SnapshotProfileOptions {}
    }

    impl Debug for SnapshotProfileOptions {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for SnapshotProfileOptions {
        fn default() -> SnapshotProfileOptions {}
    }

    impl Eq for SnapshotProfileOptions {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotProfileOptions {
        fn eq(&self, other: &SnapshotProfileOptions) -> bool {}
    }

    impl SnapshotProfileOptions {
        /// Create options with no explicit overrides.
        pub fn new() -> Self {}

        /// Return the explicit feature-policy override.
        pub fn features(&self) -> Option<&SnapshotFeatures> {}

        /// Return the explicit target override.
        pub fn target(&self) -> Option<&str> {}

        /// Return the explicit toolchain override.
        pub fn toolchain(&self) -> Option<&str> {}

        /// Select a nightly toolchain.
        pub fn with_toolchain(self, toolchain: impl Into<String>) -> Self {}

        /// Select one Cargo target triple.
        pub fn with_target(self, target: impl Into<String>) -> Self {}

        /// Select the shared Cargo feature policy.
        pub fn with_features(self, features: SnapshotFeatures) -> Self {}
    }

    impl Clone for SnapshotReport {
        fn clone(&self) -> SnapshotReport {}
    }

    impl Debug for SnapshotReport {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotReport {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotReport {
        fn eq(&self, other: &SnapshotReport) -> bool {}
    }

    impl SnapshotReport {
        /// Return file results in display order.
        pub fn changes(&self) -> &[SnapshotChange] {}

        /// Return skipped binary-only packages in package order.
        pub fn skipped_packages(&self) -> &[String] {}

        /// Return whether the destination matches the captured snapshot.
        pub fn is_current(&self) -> bool {}
    }

    impl Clone for SnapshotRequest {
        fn clone(&self) -> SnapshotRequest {}
    }

    impl Debug for SnapshotRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for SnapshotRequest {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for SnapshotRequest {
        fn eq(&self, other: &SnapshotRequest) -> bool {}
    }

    impl SnapshotRequest {
        /// Create a request for one or more local Cargo manifests or directories.
        pub fn new(inputs: Vec<PathBuf>, profile: SnapshotProfile) -> Result<Self> {}

        /// Return the input paths in caller order.
        pub fn inputs(&self) -> &[PathBuf] {}

        /// Return the resolved capture profile.
        pub fn profile(&self) -> &SnapshotProfile {}
    }

    impl Clone for ToolchainCacheStatus {
        fn clone(&self) -> ToolchainCacheStatus {}
    }

    impl Debug for ToolchainCacheStatus {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl ToolchainCacheStatus {
        /// Return the last-use time when valid metadata exists.
        pub fn last_use(&self) -> Option<SystemTime> {}

        /// Return the recognized toolchain-tree size in bytes.
        pub fn size_bytes(&self) -> u64 {}

        /// Return the recognized workspace entries in identity order.
        pub fn workspaces(&self) -> &[WorkspaceCacheStatus] {}

        /// Return the toolchain identity digest.
        pub fn identity(&self) -> &str {}

        /// Return whether another operation currently holds the toolchain lease.
        pub fn is_locked(&self) -> bool {}
    }

    impl Clone for WorkspaceCacheStatus {
        fn clone(&self) -> WorkspaceCacheStatus {}
    }

    impl Debug for WorkspaceCacheStatus {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl WorkspaceCacheStatus {
        /// Return sorted package name and version labels observed in this entry.
        pub fn packages(&self) -> &[String] {}

        /// Return the canonical workspace root when display metadata exists.
        pub fn workspace_root(&self) -> Option<&Path> {}

        /// Return the last-use time when valid metadata exists.
        pub fn last_use(&self) -> Option<SystemTime> {}

        /// Return the recognized entry size in bytes.
        pub fn size_bytes(&self) -> u64 {}

        /// Return the workspace identity digest.
        pub fn identity(&self) -> &str {}

        /// Return whether another operation currently holds the workspace lease.
        pub fn is_locked(&self) -> bool {}
    }

    impl Debug for RuskelError {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for RuskelError {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Error for RuskelError {
        fn source(
            &self,
        ) -> ::core::option::Option<&(dyn ::thiserror::__private20::Error + 'static)> {
        }
    }

    impl From<Error> for RuskelError {
        fn from(err: rust_format::Error) -> Self {}
    }

    impl From<Error> for RuskelError {
        fn from(err: serde_json::Error) -> Self {}
    }

    impl From<Error> for RuskelError {
        fn from(err: syntect::Error) -> Self {}
    }

    impl From<Error> for RuskelError {
        fn from(source: io::Error) -> Self {}
    }

    impl Debug for SnapshotStore {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl SnapshotStore {
        /// Compare or atomically update the destination with one captured snapshot.
        pub fn sync(&self, snapshot: &ApiSnapshot) -> Result<SnapshotReport> {}

        /// Open and validate one generated destination.
        pub fn open(path: impl AsRef<Path>, mode: SnapshotMode) -> Result<Self> {}
    }

    impl Default for Renderer {
        fn default() -> Self {}
    }

    impl Renderer {
        /// Apply a filter to output. The filter is a path BELOW the outermost
        /// module.
        pub fn with_filter(self, filter: &str) -> Self {}

        /// Attach optional frontmatter metadata to the rendered output.
        pub fn with_frontmatter(self, frontmatter: FrontmatterConfig) -> Self {}

        /// Create a renderer with default configuration.
        pub fn new() -> Self {}

        /// Render a crate into formatted Rust source text.
        pub fn render(&self, crate_data: &Crate) -> Result<String> {}

        /// Render impl blocks for auto traits like Send and Sync?
        pub fn with_auto_impls(self, render_auto_impls: bool) -> Self {}

        /// Render impl blocks for traits implemented for all types?
        pub fn with_blanket_impls(self, render_blanket_impls: bool) -> Self {}

        /// Render private items?
        pub fn with_private_items(self, render_private_items: bool) -> Self {}
    }
}
