// @generated by `ruskel-snapshot`; do not edit.
//
// Package: libruskel
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: ruskel, ruskel-mcp, ruskel-snapshot

//! Ruskel generates skeletonized versions of Rust crates.
//!
//! It produces a single-page, syntactically valid Rust code representation of a
//! crate, with all implementations omitted. This provides a clear overview of
//! the crate's structure and public API.
//!
//! Ruskel works by first fetching all dependencies, then using the nightly Rust
//! toolchain to generate JSON documentation data. This data is then parsed and
//! rendered into the skeletonized format. The skeletonized code is then
//! formatted with rustfmt, and optionally has syntax highlighting applied.
//!
//!
//! You must have the nightly Rust toolchain installed to use (but not to
//! install) Ruskel.
//!
//! Canonical workspace snapshots are captured separately through
//! [`Ruskel::capture_snapshot`]. Capture returns an in-memory [`ApiSnapshot`]
//! and never writes a destination directory.

use std::{
    fmt::{Binary, Debug, Display, LowerHex, Octal, UpperHex},
    hash::Hash,
    ops::{BitAnd, BitAndAssign, BitOr, BitOrAssign, BitXor, BitXorAssign, Not, Sub, SubAssign},
    path::{Path, PathBuf},
    time::SystemTime,
};

use bitflags::{
    iter::{Iter, IterNames},
    traits::{Flag, Flags, PublicFlags},
};
use rustdoc_types::{Crate, Id};

/// Complete ordered snapshot captured without destination I/O.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApiSnapshot {/* private fields */}

impl ApiSnapshot {
    /// Return generated crate files in canonical package order.
    pub fn crates(&self) -> &[CrateSnapshot];

    /// Return the complete generated workspace index.
    pub fn index(&self) -> &str;

    /// Return the canonical profile used for this capture.
    pub fn profile(&self) -> &SnapshotProfile;

    /// Return binary-only package names in canonical order.
    pub fn skipped_packages(&self) -> &[String];
}

/// A cache entry or operation that Ruskel skipped.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CacheIssue {/* private fields */}

impl CacheIssue {
    /// Return an actionable description of the issue.
    pub fn message(&self) -> &str;

    /// Return the affected path.
    pub fn path(&self) -> &Path;
}

/// A read-only snapshot of the dedicated Ruskel cache.
#[derive(Clone, Debug)]
pub struct CacheStatus {/* private fields */}

impl CacheStatus {
    /// Return usage above the soft high-water mark.
    pub fn excess_bytes(&self) -> u64;

    /// Return the canonical cache root.
    pub fn root(&self) -> &Path;

    /// Return entries that status could not safely recognize or inspect.
    pub fn skipped(&self) -> &[CacheIssue];

    /// Return recognized toolchain entries in identity order.
    pub fn toolchains(&self) -> &[ToolchainCacheStatus];

    /// Return total recognized build and trash usage in bytes.
    pub fn total_bytes(&self) -> u64;

    /// Return recognized trash usage in bytes.
    pub fn trash_bytes(&self) -> u64;
}

/// Result of one explicit cache-clean operation.
#[derive(Clone, Debug)]
pub struct CleanReport {/* private fields */}

impl CleanReport {
    /// Return removal failures.
    pub fn failures(&self) -> &[CacheIssue];

    /// Return whether the clean removed all safe entries without contention or
    /// failure.
    pub fn is_complete(&self) -> bool;

    /// Return the recognized bytes removed by this operation.
    pub fn removed_bytes(&self) -> u64;

    /// Return the number of removed toolchain and trash entries.
    pub fn removed_entries(&self) -> u64;

    /// Return the canonical cache root.
    pub fn root(&self) -> &Path;

    /// Return whether an active request prevented the clean.
    pub fn root_busy(&self) -> bool;

    /// Return unrecognized entries that the clean preserved.
    pub fn skipped(&self) -> &[CacheIssue];

    /// Return recognized usage after the clean.
    pub fn usage_after(&self) -> u64;
}

/// Cargo feature and visibility options for one crate inspection request.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CrateRequest {
    /// Build without the crate's default features.
    pub no_default_features: bool,
    /// Build with every optional feature.
    pub all_features: bool,
    /// Explicit features to enable.
    pub features: Vec<String>,
    /// Include private and crate-private items.
    pub private_items: bool,
}

/// One canonical generated crate file held in memory.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CrateSnapshot {/* private fields */}

impl CrateSnapshot {
    /// Return the complete generated Rust source.
    pub fn contents(&self) -> &str;

    /// Return the Rust library crate name.
    pub fn crate_name(&self) -> &str;

    /// Return dependency packages named by displayed public paths.
    pub fn exposes(&self) -> &[String];

    /// Return the generated filename relative to the snapshot root.
    pub fn filename(&self) -> &str;

    /// Return the number of unique rendered declarations.
    pub fn items(&self) -> usize;

    /// Return the Cargo package name.
    pub fn package(&self) -> &str;

    /// Return the first sentence of the crate documentation.
    pub fn summary(&self) -> &str;

    /// Return publicly used local items without a public path.
    pub fn unnameable(&self) -> &[String];
}

/// Binary target metadata for frontmatter rendering.
#[derive(Clone, Debug)]
pub struct FrontmatterBinaryTarget {/* private fields */}

impl FrontmatterBinaryTarget {
    /// Build a binary target descriptor for frontmatter output.
    pub fn new(name: impl Into<String>, is_bin_only: bool) -> Self;
}

/// Configuration describing optional frontmatter comments rendered ahead of
/// skeleton output.
#[derive(Clone, Debug, Default)]
pub struct FrontmatterConfig {/* private fields */}

impl FrontmatterConfig {
    /// Disable frontmatter rendering entirely.
    pub fn disabled() -> Self;

    /// Create a configuration with frontmatter enabled for the provided target
    /// specification.
    pub fn for_target(target: impl Into<String>) -> Self;

    /// Render the configured frontmatter when enabled, returning the formatted
    /// comment block.
    pub fn render(
        &self,
        include_private: bool,
        render_auto_impls: bool,
        render_blanket_impls: bool,
    ) -> Option<String>;

    /// Attach binary target metadata to the frontmatter.
    pub fn with_binary_target(self, binary_target: FrontmatterBinaryTarget) -> Self;

    /// Attach the resolved filter path used for rendering.
    pub fn with_filter(self, filter: Option<String>) -> Self;

    /// Attach search metadata summarising the invocation.
    pub fn with_search(self, search: FrontmatterSearch) -> Self;
}

/// Individual search hit included in the frontmatter summary.
#[derive(Clone, Debug)]
pub struct FrontmatterHit {/* private fields */}

impl FrontmatterHit {
    /// Build a frontmatter search hit summary.
    pub fn new(path: impl Into<String>, domains: SearchDomain) -> Self;
}

/// Summary of a search invocation attached to the frontmatter.
#[derive(Clone, Debug)]
pub struct FrontmatterSearch {/* private fields */}

impl FrontmatterSearch {
    /// Build a search summary for frontmatter output.
    pub fn new(
        query: impl Into<String>,
        domains: SearchDomain,
        case_sensitive: bool,
        expand_containers: bool,
        hits: Vec<FrontmatterHit>,
    ) -> Self;
}

/// Lightweight record describing an item for list mode output.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ListItem {
    /// Kind classification for the item.
    pub kind: SearchItemKind,
    /// Canonical path rendered as a `::` separated string.
    pub path: String,
}

/// Configurable renderer that turns rustdoc data into skeleton Rust source.
#[derive(Default)]
pub struct Renderer {/* private fields */}

impl Renderer {
    /// Create a renderer with default configuration.
    pub fn new() -> Self;

    /// Render a crate into formatted Rust source text.
    pub fn render(&self, crate_data: &Crate) -> crate::Result<String>;

    /// Render impl blocks for auto traits like Send and Sync?
    pub fn with_auto_impls(self, render_auto_impls: bool) -> Self;

    /// Render impl blocks for traits implemented for all types?
    pub fn with_blanket_impls(self, render_blanket_impls: bool) -> Self;

    /// Apply a filter to output. The filter is a path BELOW the outermost
    /// module.
    pub fn with_filter(self, filter: &str) -> Self;

    /// Attach optional frontmatter metadata to the rendered output.
    pub fn with_frontmatter(self, frontmatter: FrontmatterConfig) -> Self;

    /// Render private items?
    pub fn with_private_items(self, render_private_items: bool) -> Self;
}

/// Convenience alias for results returned by libruskel operations.
pub type Result<T> = Result<T, RuskelError>;

/// Ruskel generates a skeletonized version of a Rust crate in a single page.
/// It produces syntactically valid Rust code with all implementations omitted.
///
/// The tool performs a 'cargo fetch' to ensure all referenced code is available
/// locally, then uses 'cargo doc' with the nightly toolchain to generate JSON
/// output. This JSON is parsed and used to render the skeletonized code. Users
/// must have the nightly Rust toolchain installed and available.
#[derive(Clone, Debug, Default)]
pub struct Ruskel {/* private fields */}

impl Ruskel {
    /// Return a read-only snapshot of the dedicated cache.
    pub fn cache_status(&self) -> crate::Result<CacheStatus>;

    /// Capture canonical public APIs for local Cargo inputs entirely in memory.
    ///
    /// Snapshot capture uses this instance's cache, offline, and silent
    /// settings. Interactive rendering options do not affect the artifact.
    pub fn capture_snapshot(&self, request: &SnapshotRequest) -> crate::Result<ApiSnapshot>;

    /// Remove cache-owned build data when no request is active.
    pub fn clean_cache(&self) -> crate::Result<CleanReport>;

    /// Returns the parsed representation of the crate's API.
    ///
    /// # Arguments
    /// * `target` - The target specification (see new() documentation for
    ///   format)
    /// * `request` - Cargo feature and visibility options
    pub fn inspect(&self, target: &str, request: &CrateRequest) -> crate::Result<Crate>;

    /// Produce a lightweight listing of crate items, optionally filtered by a
    /// search query.
    pub fn list(
        &self,
        target: &str,
        request: &CrateRequest,
        search: Option<&SearchOptions>,
    ) -> crate::Result<Vec<ListItem>>;

    /// Creates a new Ruskel instance with default configuration.
    ///
    /// # Target Format
    ///
    /// A target specification is an entrypoint, followed by an optional path,
    /// with components separated by '::'.
    ///
    ///   entrypoint::path
    ///
    /// An entrypoint can be:
    ///
    /// - A path to a Rust file
    /// - A directory containing a Cargo.toml file
    /// - A module name
    /// - A package name. In this case the name can also include a version
    ///   number, separated by an '@' symbol.
    ///
    /// Ruskel selects workspace members before direct dependencies. It matches
    /// a direct dependency by its `Cargo.toml` key. If neither exists, it
    /// resolves the name through the configured Cargo registry. The path
    /// after the first `::` stays inside the selected entrypoint.
    ///
    /// # Examples of valid targets:
    ///
    /// - src/lib.rs
    /// - my_module
    /// - serde
    /// - rustdoc-types
    /// - serde::Deserialize
    /// - serde@1.0
    /// - rustdoc-types::Crate
    /// - rustdoc_types::Crate
    pub fn new() -> Self;

    /// Returns a pretty-printed version of the crate's JSON representation.
    ///
    /// # Arguments
    /// * `target` - The target specification (see new() documentation for
    ///   format)
    /// * `request` - Cargo feature and visibility options
    pub fn raw_json(&self, target: &str, request: &CrateRequest) -> crate::Result<String>;

    /// Render the crate target into a Rust skeleton without filtering.
    pub fn render(&self, target: &str, request: &CrateRequest) -> crate::Result<String>;

    /// Execute a search against the crate and return the matched items along
    /// with a rendered skeleton.
    ///
    /// The search respects the same target resolution logic as
    /// [`Self::render`], but only the matched items and their ancestors are
    /// emitted in the final skeleton.
    pub fn search(
        &self,
        target: &str,
        request: &CrateRequest,
        options: &SearchOptions,
    ) -> crate::Result<SearchResponse>;

    /// Enables or disables rendering of auto-implemented traits.
    pub fn with_auto_impls(self, auto_impls: bool) -> Self;

    /// Overrides the binary target used when rendering a crate.
    pub fn with_bin_target(self, bin_target: Option<String>) -> Self;

    /// Override the dedicated cache root.
    ///
    /// Pass `None` to restore `RUSKEL_CACHE_DIR` and platform cache resolution.
    pub fn with_cache_dir(self, dir: Option<PathBuf>) -> Self;

    /// Enables or disables frontmatter emission on rendered output.
    pub fn with_frontmatter(self, frontmatter: bool) -> Self;

    /// Enables or disables offline mode, which prevents Ruskel from fetching
    /// dependencies from the network.
    pub fn with_offline(self, offline: bool) -> Self;

    /// Enables or disables silent mode, which suppresses output during
    /// processing.
    pub fn with_silent(self, silent: bool) -> Self;
}

/// Errors surfaced while generating rustdoc skeletons.
#[derive(Debug, Display, std::error::Error)]
pub enum RuskelError {
    /// Indicates that a snapshot profile is invalid or unavailable.
    #[error("Invalid snapshot profile: {0}")]
    SnapshotProfile(String),
    /// Indicates that an input could not be discovered as a snapshot package.
    #[error("Snapshot discovery failed for '{}': {message}", input.display())]
    SnapshotDiscovery {
        /// Input path associated with the failure.
        input: PathBuf,
        /// Actionable discovery failure.
        message: String,
    },
    /// Indicates that rustdoc generation failed for a selected package.
    #[error("Snapshot capture failed for package '{package}': {message}")]
    SnapshotCapture {
        /// Selected Cargo package.
        package: String,
        /// Underlying build failure.
        message: String,
    },
    /// Indicates that strict snapshot rendering rejected a public surface.
    #[error("Snapshot rendering failed for package '{package}': {message}")]
    SnapshotRender {
        /// Selected Cargo package.
        package: String,
        /// Underlying fidelity or formatting failure.
        message: String,
    },
    /// Indicates that snapshot persistence failed for a destination path.
    #[error("Snapshot store failed for '{}': {message}", path.display())]
    SnapshotStore {
        /// Destination path associated with the failure.
        path: PathBuf,
        /// Actionable persistence failure.
        message: String,
    },
    /// Indicates that a specified module could not be found.
    #[error("Module not found: {0}")]
    ModuleNotFound(String),
    /// Indicates a failure in reading a file, wrapping the underlying IO error.
    #[error("Failed to read file: {0}")]
    FileRead(std::io::Error),
    /// Indicates an I/O failure in a cache-owned path.
    #[error("Cache {action} failed for '{}': {source}", path.display())]
    CacheIo {
        /// Operation that failed.
        action: &'static str,
        /// Cache-owned path associated with the failure.
        path: PathBuf,
        /// Underlying filesystem error.
        #[source]
        source: std::io::Error,
    },
    /// Indicates that a cache root or entry has an invalid layout.
    #[error("Invalid Ruskel cache at '{}': {message}", path.display())]
    CacheLayout {
        /// Path that failed validation.
        path: PathBuf,
        /// Actionable validation failure.
        message: String,
    },
    /// Indicates a failure in the code generation process.
    #[error("{0}")]
    Generate(String),
    /// Indicates an item referenced by rustdoc output could not be found.
    #[error("Item not found in rustdoc index: {0}")]
    ItemNotFound(String),
    /// Indicates an error occurred while executing a Cargo command.
    #[error("Cargo error: {0}")]
    Cargo(String),
    /// Indicates an error occurred during code formatting.
    #[error("Formatting error: {0}")]
    Format(String),
    /// Indicates an error occurred during syntax highlighting.
    #[error("Highlighting error: {0}")]
    Highlight(String),
    /// The specified filter did not match any items.
    #[error("Filter '{0}' did not match any items")]
    FilterNotMatched(String),
    /// Failed to parse a Cargo.toml manifest
    #[error("Failed to parse Cargo.toml manifest: {0}")]
    ManifestParse(String),
    /// Indicates that the Cargo.toml manifest file could not be found in the
    /// current directory or any parent directories.
    #[error("Failed to find Cargo.toml in the current directory or any parent directories")]
    ManifestNotFound,
    /// Indicates an invalid version string was provided.
    #[error("Invalid version: {0}")]
    InvalidVersion(String),
    /// Indicates an invalid target specification was provided.
    #[error("Invalid target: {0}")]
    InvalidTarget(String),
    /// Indicates a dependency was not found in the registry.
    #[error("No matching package")]
    DependencyNotFound,
}

impl From<rust_format::Error> for RuskelError {}

impl From<serde_json::Error> for RuskelError {}

impl From<std::io::Error> for RuskelError {}

impl From<syntect::Error> for RuskelError {}

/// Domains that a search query can operate over.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct SearchDomain(_);

impl SearchDomain {
    /// Get a flags value with all known bits set.
    pub const fn all() -> Self;

    /// Get the underlying bits value.
    ///
    /// The returned value is exactly the bits set in this flags value.
    pub const fn bits(&self) -> u32;

    /// The bitwise negation (`!`) of the bits in `self`, truncating the result.
    #[must_use]
    pub const fn complement(self) -> Self;

    /// Whether all set bits in `other` are also set in `self`.
    pub const fn contains(&self, other: Self) -> bool;

    /// The intersection of `self` with the complement of `other` (`&!`).
    ///
    /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
    /// `difference` won't truncate `other`, but the `!` operator will.
    #[must_use]
    pub const fn difference(self, other: Self) -> Self;

    /// Get a flags value with all bits unset.
    pub const fn empty() -> Self;

    /// Convert from a bits value.
    ///
    /// This method will return `None` if any unknown bits are set.
    pub const fn from_bits(bits: u32) -> Option<Self>;

    /// Convert from a bits value exactly.
    pub const fn from_bits_retain(bits: u32) -> Self;

    /// Convert from a bits value, unsetting any unknown bits.
    pub const fn from_bits_truncate(bits: u32) -> Self;

    /// Get a flags value with the bits of a flag with the given name set.
    ///
    /// This method will return `None` if `name` is empty or doesn't
    /// correspond to any named flag.
    pub fn from_name(name: &str) -> Option<Self>;

    /// The bitwise or (`|`) of the bits in `self` and `other`.
    pub fn insert(&mut self, other: Self);

    /// The bitwise and (`&`) of the bits in `self` and `other`.
    #[must_use]
    pub const fn intersection(self, other: Self) -> Self;

    /// Whether any set bits in `other` are also set in `self`.
    pub const fn intersects(&self, other: Self) -> bool;

    /// Whether all known bits in this flags value are set.
    pub const fn is_all(&self) -> bool;

    /// Whether all bits in `self` are unset.
    pub const fn is_empty(&self) -> bool;

    /// The bitwise or (`|`) of the bits in `self` and `other`.
    #[must_use]
    pub const fn r#union(self, other: Self) -> Self;

    /// The intersection of `self` with the complement of `other` (`&!`).
    ///
    /// This method is not equivalent to `self & !other` when `other` has unknown bits set.
    /// `remove` won't truncate `other`, but the `!` operator will.
    pub fn remove(&mut self, other: Self);

    /// Call `insert` when `value` is `true` or `remove` when `value` is `false`.
    pub fn set(&mut self, other: Self, value: bool);

    /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
    #[must_use]
    pub const fn symmetric_difference(self, other: Self) -> Self;

    /// The bitwise exclusive-or (`^`) of the bits in `self` and `other`.
    pub fn toggle(&mut self, other: Self);
}

impl SearchDomain {
    /// Match against documentation strings.
    pub const DOCS: Self = _;
    /// Match against item names.
    pub const NAMES: Self = _;
    /// Match against canonical module paths.
    pub const PATHS: Self = _;
    /// Match against rendered item signatures.
    pub const SIGNATURES: Self = _;
}

impl SearchDomain {
    /// Return human-friendly labels for every selected domain.
    pub fn labels(self) -> Vec<&'static str>;

    /// Parse one case-insensitive search-domain token.
    pub fn parse(token: &str) -> Result<Self, String>;
}

impl SearchDomain {
    /// Yield a set of contained flags values.
    ///
    /// Each yielded flags value will correspond to a defined named flag. Any unknown bits
    /// will be yielded together as a final flags value.
    pub const fn iter(&self) -> Iter<SearchDomain>;

    /// Yield a set of contained named flags values.
    ///
    /// This method is like [`iter`](#method.iter), except only yields bits in contained named flags.
    /// Any unknown bits, or bits not corresponding to a contained flag will not be yielded.
    pub const fn iter_names(&self) -> IterNames<SearchDomain>;
}

impl Binary for SearchDomain {}

impl BitAnd for SearchDomain {
    type Output = SearchDomain;
}

impl BitAndAssign for SearchDomain {}

impl BitOr for SearchDomain {
    type Output = SearchDomain;
}

impl BitOrAssign for SearchDomain {}

impl BitXor for SearchDomain {
    type Output = SearchDomain;
}

impl BitXorAssign for SearchDomain {}

impl Extend<SearchDomain> for SearchDomain {}

impl Flags for SearchDomain {
    type Bits = u32;
    const FLAGS: &'static [Flag<SearchDomain>] = _;
}

impl FromIterator<SearchDomain> for SearchDomain {}

impl IntoIterator for SearchDomain {
    type IntoIter = Iter<SearchDomain>;
    type Item = SearchDomain;
}

impl LowerHex for SearchDomain {}

impl Not for SearchDomain {
    type Output = SearchDomain;
}

impl Octal for SearchDomain {}

impl PublicFlags for SearchDomain {
    type Internal = InternalBitFlags;
    type Primitive = u32;
}

impl Sub for SearchDomain {
    type Output = SearchDomain;
}

impl SubAssign for SearchDomain {}

impl UpperHex for SearchDomain {}

/// Classified kind associated with a search result.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SearchItemKind {
    /// Synthetic crate root module.
    Crate,
    /// Regular module.
    Module,
    /// Struct definition.
    Struct,
    /// Union definition.
    Union,
    /// Enum definition.
    Enum,
    /// Variant within an enum.
    EnumVariant,
    /// Named or positional field within a struct or union.
    Field,
    /// Trait definition.
    Trait,
    /// Trait alias definition.
    TraitAlias,
    /// Free function.
    Function,
    /// Method inside an impl block.
    Method,
    /// Trait method declaration.
    TraitMethod,
    /// Associated constant.
    AssocConst,
    /// Associated type.
    AssocType,
    /// Top-level constant.
    Constant,
    /// Static item.
    Static,
    /// Type alias.
    TypeAlias,
    /// `use` declaration.
    Use,
    /// Macro_rules! definition.
    Macro,
    /// Procedural macro entrypoint.
    ProcMacro,
    /// Primitive type description.
    Primitive,
    /// Synthetic segment representing an impl target.
    ImplTarget,
}

impl SearchItemKind {
    /// Human-friendly label describing the item kind.
    pub fn label(self) -> &'static str;
}

/// Options that control how a crate search should be performed.
#[derive(Clone, Debug)]
pub struct SearchOptions {
    /// Raw user query to evaluate.
    pub query: String,
    /// Domains to search across; defaults to [`SearchDomain::default`].
    pub domains: SearchDomain,
    /// Whether matching should respect letter casing.
    pub case_sensitive: bool,
    /// Whether matched container items should expand to include their children.
    pub expand_containers: bool,
}

impl SearchOptions {
    /// Create fully-specified search options with transport-independent
    /// defaults.
    pub fn configured(
        query: impl Into<String>,
        domains: SearchDomain,
        case_sensitive: bool,
        expand_containers: bool,
    ) -> Self;

    /// Ensure the options have at least one domain selected.
    pub fn ensure_domains(&mut self);

    /// Create a new options struct with the provided query string.
    pub fn new(query: impl Into<String>) -> Self;
}

/// Component in a canonical path leading to an item.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SearchPathSegment {
    /// Raw identifier for the segment without keyword escaping.
    pub name: String,
    /// Display name used when rendering the path.
    pub display_name: String,
    /// Classification of the segment.
    pub kind: SearchItemKind,
    /// Whether the segment corresponds to a publicly visible item.
    pub is_public: bool,
}

/// Aggregated search response containing matches and rendered output.
#[derive(Clone, Debug)]
pub struct SearchResponse {
    /// Matched records returned by the query.
    pub results: Vec<SearchResult>,
    /// Rendered skeleton filtered to only include matched items.
    pub rendered: String,
}

/// Result of performing a query against a crate index.
#[derive(Clone, Debug)]
pub struct SearchResult {
    /// Identifier of the matching item.
    pub item_id: Id,
    /// Kind of result item.
    pub kind: SearchItemKind,
    /// Canonical path segments to reach the item.
    pub path: Vec<SearchPathSegment>,
    /// Canonical path rendered as a `::` separated string.
    pub path_string: String,
    /// Raw identifier of the item.
    pub raw_name: String,
    /// Display name formatted for rendering.
    pub display_name: String,
    /// Documentation snippet if available.
    pub docs: Option<String>,
    /// Rendered signature used for matching and display.
    pub signature: Option<String>,
    /// Ancestor chain of items that must be rendered for context.
    pub ancestors: Vec<Id>,
    /// Domains that produced a match for this query result.
    pub matched: SearchDomain,
}

/// One path and its typed comparison result.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotChange {/* private fields */}

impl SnapshotChange {
    /// Return the comparison result.
    pub fn kind(&self) -> SnapshotChangeKind;

    /// Return the path relative to the snapshot parent.
    pub fn path(&self) -> &Path;
}

/// One typed snapshot comparison result.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SnapshotChangeKind {
    /// The captured entry does not exist in the stored tree.
    Added,
    /// The captured and stored entry bytes differ.
    Changed,
    /// A previously managed entry is no longer captured.
    Removed,
    /// The captured and stored entry bytes are identical.
    Unchanged,
    /// The destination contains an entry that Ruskel does not own.
    Unexpected,
    /// A bounded backup shows an interrupted directory swap.
    Interrupted,
}

/// Cargo feature policy shared by every crate in one snapshot.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct SnapshotFeatures {/* private fields */}

impl SnapshotFeatures {
    /// Return whether Cargo enables every feature.
    pub fn all_features(&self) -> bool;

    /// Return whether Cargo enables each package's default features.
    pub fn default_features(&self) -> bool;

    /// Return the sorted selected feature list.
    pub fn features(&self) -> &[String];

    /// Validate and canonicalize one snapshot feature policy.
    pub fn new(
        default_features: bool,
        all_features: bool,
        features: Vec<String>,
    ) -> crate::Result<Self>;
}

/// Persistence behavior for one snapshot destination.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum SnapshotMode {
    /// Replace the generated tree when captured bytes differ.
    Update,
    /// Compare captured bytes without changing the generated tree.
    Check,
}

/// Fully resolved capture profile for one invocation.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotProfile {/* private fields */}

impl SnapshotProfile {
    /// Return the shared Cargo feature policy.
    pub fn features(&self) -> &SnapshotFeatures;

    /// Validate a complete profile against the local Rust installation.
    pub fn new(
        toolchain: impl Into<String>,
        target: impl Into<String>,
        features: SnapshotFeatures,
    ) -> crate::Result<Self>;

    /// Resolve explicit overrides and invocation defaults as one profile.
    pub fn resolve(options: SnapshotProfileOptions) -> crate::Result<Self>;

    /// Return the selected Cargo target triple.
    pub fn target(&self) -> &str;

    /// Return the selected nightly toolchain.
    pub fn toolchain(&self) -> &str;
}

/// Optional capture profile overrides.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct SnapshotProfileOptions {/* private fields */}

impl SnapshotProfileOptions {
    /// Return the explicit feature-policy override.
    pub fn features(&self) -> Option<&SnapshotFeatures>;

    /// Create options with no explicit overrides.
    pub fn new() -> Self;

    /// Return the explicit target override.
    pub fn target(&self) -> Option<&str>;

    /// Return the explicit toolchain override.
    pub fn toolchain(&self) -> Option<&str>;

    /// Select the shared Cargo feature policy.
    pub fn with_features(self, features: SnapshotFeatures) -> Self;

    /// Select one Cargo target triple.
    pub fn with_target(self, target: impl Into<String>) -> Self;

    /// Select a nightly toolchain.
    pub fn with_toolchain(self, toolchain: impl Into<String>) -> Self;
}

/// Complete ordered result from one snapshot synchronization.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotReport {/* private fields */}

impl SnapshotReport {
    /// Return file results in display order.
    pub fn changes(&self) -> &[SnapshotChange];

    /// Return whether the destination matches the captured snapshot.
    pub fn is_current(&self) -> bool;

    /// Return skipped binary-only packages in package order.
    pub fn skipped_packages(&self) -> &[String];
}

/// Inputs and resolved profile for one in-memory capture.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SnapshotRequest {/* private fields */}

impl SnapshotRequest {
    /// Return the input paths in caller order.
    pub fn inputs(&self) -> &[PathBuf];

    /// Create a request for one or more local Cargo manifests or directories.
    pub fn new(inputs: Vec<PathBuf>, profile: SnapshotProfile) -> crate::Result<Self>;

    /// Return the resolved capture profile.
    pub fn profile(&self) -> &SnapshotProfile;
}

/// One physically resolved snapshot destination.
#[derive(Debug)]
pub struct SnapshotStore {/* private fields */}

impl SnapshotStore {
    /// Open and validate one generated destination.
    pub fn open(path: impl AsRef<Path>, mode: SnapshotMode) -> crate::Result<Self>;

    /// Compare or atomically update the destination with one captured snapshot.
    pub fn sync(&self, snapshot: &ApiSnapshot) -> crate::Result<SnapshotReport>;
}

/// Status for one nightly toolchain entry in the cache.
#[derive(Clone, Debug)]
pub struct ToolchainCacheStatus {/* private fields */}

impl ToolchainCacheStatus {
    /// Return the toolchain identity digest.
    pub fn identity(&self) -> &str;

    /// Return whether another operation currently holds the toolchain lease.
    pub fn is_locked(&self) -> bool;

    /// Return the last-use time when valid metadata exists.
    pub fn last_use(&self) -> Option<SystemTime>;

    /// Return the recognized toolchain-tree size in bytes.
    pub fn size_bytes(&self) -> u64;

    /// Return the recognized workspace entries in identity order.
    pub fn workspaces(&self) -> &[WorkspaceCacheStatus];
}

/// Status for one workspace entry in the cache.
#[derive(Clone, Debug)]
pub struct WorkspaceCacheStatus {/* private fields */}

impl WorkspaceCacheStatus {
    /// Return the workspace identity digest.
    pub fn identity(&self) -> &str;

    /// Return whether another operation currently holds the workspace lease.
    pub fn is_locked(&self) -> bool;

    /// Return the last-use time when valid metadata exists.
    pub fn last_use(&self) -> Option<SystemTime>;

    /// Return sorted package name and version labels observed in this entry.
    pub fn packages(&self) -> &[String];

    /// Return the recognized entry size in bytes.
    pub fn size_bytes(&self) -> u64;

    /// Return the canonical workspace root when display metadata exists.
    pub fn workspace_root(&self) -> Option<&Path>;
}

pub mod highlight {
    //! Syntax highlighting functionality for Rust code.

    /// Applies syntax highlighting to Rust code using the Solarized (dark) theme.
    ///
    /// # Arguments
    /// * `code` - The Rust code to highlight
    ///
    /// # Returns
    /// A string with ANSI escape codes for terminal color output
    pub fn highlight_code(code: &str) -> crate::Result<String>;
}

pub mod toolchain {
    //! Shared nightly/rustup helpers.
    //! Shared nightly and `rustup` helpers.

    /// Return the active portable dated-nightly toolchain name.
    pub fn active_dated_nightly() -> crate::Result<String>;

    /// Ensure the nightly toolchain exists and report whether the `rust-docs-json`
    /// component is installed.
    pub fn ensure_nightly_with_docs() -> crate::Result<bool>;

    /// Return the host target reported by the selected compiler.
    pub fn host_target(toolchain: &str) -> crate::Result<String>;

    /// Locate the nightly toolchain sysroot path.
    pub fn nightly_sysroot() -> crate::Result<PathBuf>;

    /// Locate a binary installed for the selected toolchain.
    pub fn toolchain_binary(toolchain: &str, binary: &str) -> crate::Result<PathBuf>;

    /// Return the SHA-256 identity of one compiler description.
    pub fn toolchain_identity(toolchain: &str) -> crate::Result<String>;
}
