// @generated by `ruskel-snapshot`; do not edit.

pub mod ruskel_mcp {
    //! MCP server integration for the `ruskel` CLI.

    #[doc(hidden)]
    /// MCP server implementation that forwards requests to an underlying `Ruskel`
    /// instance.
    pub struct RuskelServer {}

    #[doc(hidden)]
    /// Default request values applied by the MCP server when a tool call omits
    /// them.
    pub struct RuskelServerDefaults {
        /// Whether omitted requests should include private items.
        pub private: bool,
        /// Whether omitted requests should include frontmatter comments.
        pub frontmatter: bool,
    }

    /// Serve the ruskel MCP API over TCP or stdio depending on configuration.
    ///
    /// When `addr` is provided a TCP listener is started; otherwise the server
    /// exposes stdio pipes suitable for process integration.
    pub async fn run_mcp_server(
        ruskel: libruskel::Ruskel,
        addr: Option<String>,
        log_level: Option<tracing_subscriber::filter::LevelFilter>,
        defaults: RuskelServerDefaults,
    ) -> tmcp::Result<()> {
    }

    impl Clone for RuskelServer {
        fn clone(&self) -> RuskelServer {}
    }

    impl RuskelServer {
        /// Create a new server wrapper around the provided `Ruskel` renderer.
        pub fn new(ruskel: Ruskel) -> Self {}

        /// Create a new server wrapper with explicit request defaults.
        pub fn with_defaults(ruskel: Ruskel, defaults: RuskelServerDefaults) -> Self {}

        /// Exact names of tools declared as methods on this server.
        pub const NAMES: &'static [&'static str] = _;
    }

    impl ServerHandler for RuskelServer {
        fn call_tool<'life0, 'life1, 'async_trait>(
            &self,
            context: &'life1 ::tmcp::ServerCtx,
            name: String,
            arguments: Option<::tmcp::Arguments>,
            task: Option<::tmcp::schema::TaskMetadata>,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<
                        Output = ::tmcp::Result<::tmcp::schema::CallToolResponse>,
                    > + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            'life1: 'async_trait,
            Self: 'async_trait, {
        }

        fn initialize<'life0, 'life1, 'async_trait>(
            &self,
            _context: &'life1 ::tmcp::ServerCtx,
            protocol_version: ::tmcp::schema::ProtocolVersion,
            _capabilities: ::tmcp::schema::ClientCapabilities,
            _client_info: ::tmcp::schema::Implementation,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<
                        Output = ::tmcp::Result<::tmcp::schema::InitializeResult>,
                    > + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            'life1: 'async_trait,
            Self: 'async_trait, {
        }

        fn list_tools<'life0, 'life1, 'async_trait>(
            &self,
            _context: &'life1 ::tmcp::ServerCtx,
            _cursor: Option<::tmcp::schema::Cursor>,
        ) -> ::core::pin::Pin<
            Box<
                dyn ::core::future::Future<Output = ::tmcp::Result<::tmcp::schema::ListToolsResult>>
                    + ::core::marker::Send
                    + 'async_trait,
            >,
        >
        where
            'life0: 'async_trait,
            'life1: 'async_trait,
            Self: 'async_trait, {
        }
    }

    impl Clone for RuskelServerDefaults {
        fn clone(&self) -> RuskelServerDefaults {}
    }

    impl Debug for RuskelServerDefaults {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for RuskelServerDefaults {
        fn default() -> Self {}
    }
}
