// @generated by `ruskel-snapshot`; do not edit.
//
// Package: ruskel-mcp
// Publish: crates.io
// Workspace dependencies: libruskel
// Workspace dependents: ruskel

//! MCP server integration for the `ruskel` CLI.

use std::fmt::Debug;

use libruskel::Ruskel;
use tmcp::connection::ServerHandler;
use tracing_subscriber::filter::LevelFilter;

/// MCP server implementation that forwards requests to an underlying `Ruskel`
/// instance.
#[derive(Clone)]
#[doc(hidden)]
pub struct RuskelServer {/* private fields */}

impl RuskelServer {
    /// Create a new server wrapper around the provided `Ruskel` renderer.
    pub fn new(ruskel: Ruskel) -> Self;

    /// Create a new server wrapper with explicit request defaults.
    pub fn with_defaults(ruskel: Ruskel, defaults: RuskelServerDefaults) -> Self;
}

impl RuskelServer {
    /// Exact names of tools declared as methods on this server.
    pub const NAMES: &'static [&'static str] = _;
}

impl ServerHandler for RuskelServer {}

/// Default request values applied by the MCP server when a tool call omits
/// them.
#[derive(Clone, Copy, Debug, Default)]
#[doc(hidden)]
pub struct RuskelServerDefaults {
    /// Whether omitted requests should include private items.
    pub private: bool,
    /// Whether omitted requests should include frontmatter comments.
    pub frontmatter: bool,
}

/// Serve the ruskel MCP API over TCP or stdio depending on configuration.
///
/// When `addr` is provided a TCP listener is started; otherwise the server
/// exposes stdio pipes suitable for process integration.
pub async fn run_mcp_server(
    ruskel: Ruskel,
    addr: Option<String>,
    log_level: Option<LevelFilter>,
    defaults: RuskelServerDefaults,
) -> tmcp::Result<()>;
